// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Why one statement was flagged.
enum FaktaMasalah {
  /// No `segmen` cited at all. Mild: the statement may still be true.
  tanpaRujukan,

  /// A cited segment number does not exist in this transcript.
  rujukanTidakSah,

  /// Too few of the statement's content words occur anywhere in the
  /// transcript. This is the invention signal.
  dukunganLemah,

  /// The statement is supported by the transcript, but not by the
  /// segments it cited — the citation points somewhere else.
  rujukanMeleset,

  /// A number in the statement is nowhere in the transcript.
  angkaTidakAda,

  /// A proper name in the statement is nowhere in the transcript.
  namaTidakAda,
}

/// The result of a whole "Periksa fakta" pass.
class LaporanFakta {
  final List<TemuanFakta> temuan;

  /// Statements examined.
  final int diperiksa;

  /// Statements with no finding at all.
  final int bersih;

  const LaporanFakta({
    required this.temuan,
    required this.diperiksa,
    required this.bersih,
  });

  @override
  int get hashCode => temuan.hashCode ^ diperiksa.hashCode ^ bersih.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaporanFakta &&
          runtimeType == other.runtimeType &&
          temuan == other.temuan &&
          diperiksa == other.diperiksa &&
          bersih == other.bersih;
}

/// One flagged statement.
class TemuanFakta {
  /// Section heading the statement came from, in Indonesian.
  final String bagian;

  /// The statement, verbatim.
  final String pernyataan;
  final FaktaMasalah masalah;

  /// What exactly was not found, so the notulis can check it.
  final String rincian;

  const TemuanFakta({
    required this.bagian,
    required this.pernyataan,
    required this.masalah,
    required this.rincian,
  });

  @override
  int get hashCode =>
      bagian.hashCode ^
      pernyataan.hashCode ^
      masalah.hashCode ^
      rincian.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemuanFakta &&
          runtimeType == other.runtimeType &&
          bagian == other.bagian &&
          pernyataan == other.pernyataan &&
          masalah == other.masalah &&
          rincian == other.rincian;
}
