// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One register problem found in the text.
class RegisterFinding {
  final RegisterRule rule;

  /// The offending text, exactly as it appears.
  final String ditemukan;

  /// The baku replacement, or an explanation when there is no single
  /// replacement.
  final String saran;

  /// 1-based line number in the checked text.
  final int baris;

  /// True when [`normalise`] will apply `saran` automatically.
  final bool otomatis;

  const RegisterFinding({
    required this.rule,
    required this.ditemukan,
    required this.saran,
    required this.baris,
    required this.otomatis,
  });

  @override
  int get hashCode =>
      rule.hashCode ^
      ditemukan.hashCode ^
      saran.hashCode ^
      baris.hashCode ^
      otomatis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RegisterFinding &&
          runtimeType == other.runtimeType &&
          rule == other.rule &&
          ditemukan == other.ditemukan &&
          saran == other.saran &&
          baris == other.baris &&
          otomatis == other.otomatis;
}

/// Which rule a finding comes from, so the UI can group and the report
/// can cite.
enum RegisterRule {
  /// Colloquial word with no place in a naskah dinas ("bikin", "oke").
  kataTidakBaku,

  /// Misspelling of a word whose baku form is in the KBBI
  /// ("analisa" → "analisis").
  ejaanBaku,

  /// Time, money or date written outside the Pedoman's format
  /// ("Jam 09:00" → "pukul 09.00 WIB").
  formatAngka,

  /// Phrasing the Pedoman forbids ("dan lain-lain" in a naskah resmi).
  gayaDinas,
}
