// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Which required sections a parsed notulen actually filled.
class StructureReport {
  /// Headings that are required and empty, in Bahasa Indonesia.
  final List<String> bagianKosong;

  /// Required sections filled, over required sections total.
  final int terisi;
  final int wajib;

  const StructureReport({
    required this.bagianKosong,
    required this.terisi,
    required this.wajib,
  });

  @override
  int get hashCode => bagianKosong.hashCode ^ terisi.hashCode ^ wajib.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StructureReport &&
          runtimeType == other.runtimeType &&
          bagianKosong == other.bagianKosong &&
          terisi == other.terisi &&
          wajib == other.wajib;
}
