// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One row of "Tindak Lanjut".
class ActionItem {
  /// Stable within a session, so the UI can edit a row without
  /// renumbering the rest and the `.ics` UID stays the same across
  /// re-exports.
  final String id;
  final String tugas;
  final String penanggungJawab;

  /// As written: "Jumat", "12 Oktober", "akhir bulan". Kept verbatim
  /// because an un-parseable deadline is still information, and
  /// normalising it to a date the model guessed would be worse.
  final String tenggat;
  final ActionStatus status;

  /// Transcript segment indices the model cited, so the checklist can
  /// jump to where the task was agreed (shares F7's machinery).
  final Uint32List segmentIds;

  const ActionItem({
    required this.id,
    required this.tugas,
    required this.penanggungJawab,
    required this.tenggat,
    required this.status,
    required this.segmentIds,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      tugas.hashCode ^
      penanggungJawab.hashCode ^
      tenggat.hashCode ^
      status.hashCode ^
      segmentIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActionItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          tugas == other.tugas &&
          penanggungJawab == other.penanggungJawab &&
          tenggat == other.tenggat &&
          status == other.status &&
          segmentIds == other.segmentIds;
}

/// Where a task stands. Mirrors what a notulis writes in the column.
enum ActionStatus { belum, berjalan, selesai, dibatalkan }
