// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio.dart';
import 'audio/device.dart';
import 'decode.dart';
import 'doctor.dart';
import 'error.dart';
import 'export.dart';
import 'frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'session.dart';
import 'settings.dart';
import 'stt/file.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<AppConfig> getAppConfig() => RustLib.instance.api.crateApiGetAppConfig();

Future<List<Check>> runPreflightChecks() =>
    RustLib.instance.api.crateApiRunPreflightChecks();

Future<String> formatPreflightChecks({required List<Check> checks}) =>
    RustLib.instance.api.crateApiFormatPreflightChecks(checks: checks);

Future<List<String>> resumePendingTranscriptions({
  required String libraryPath,
}) => RustLib.instance.api.crateApiResumePendingTranscriptions(
  libraryPath: libraryPath,
);

/// Installs a `tracing` subscriber writing to stderr. Without this,
/// every `tracing::error!`/`warn!` call in the engine (session/pipeline
/// failures, capture errors, etc.) is silently dropped — there is no
/// default subscriber. Call once, right after `RustLib.init()`, before
/// anything else. Safe to call more than once (subsequent calls are a
/// harmless no-op via `try_init`).
Future<void> initLogging() => RustLib.instance.api.crateApiInitLogging();

Future<String> engineVersion() => RustLib.instance.api.crateApiEngineVersion();

Future<bool> healthCheck() => RustLib.instance.api.crateApiHealthCheck();

Future<List<AudioDeviceInfo>> listAudioDevices() =>
    RustLib.instance.api.crateApiListAudioDevices();

Future<AudioDeviceInfo> getLoopbackDevice({required String nameHint}) =>
    RustLib.instance.api.crateApiGetLoopbackDevice(nameHint: nameHint);

Future<String> startSession({required SessionConfig config}) =>
    RustLib.instance.api.crateApiStartSession(config: config);

Future<void> stopSession({required String sessionId}) =>
    RustLib.instance.api.crateApiStopSession(sessionId: sessionId);

Future<void> toggleMic({required String sessionId, required bool enabled}) =>
    RustLib.instance.api.crateApiToggleMic(
      sessionId: sessionId,
      enabled: enabled,
    );

Future<void> toggleSpeaker({
  required String sessionId,
  required bool enabled,
}) => RustLib.instance.api.crateApiToggleSpeaker(
  sessionId: sessionId,
  enabled: enabled,
);

Future<void> setSessionMode({
  required String sessionId,
  required SessionMode mode,
}) => RustLib.instance.api.crateApiSetSessionMode(
  sessionId: sessionId,
  mode: mode,
);

Future<SessionStatus> getSessionStatus({required String sessionId}) =>
    RustLib.instance.api.crateApiGetSessionStatus(sessionId: sessionId);

Future<List<SessionEvent>> pollSessionEvents({required String sessionId}) =>
    RustLib.instance.api.crateApiPollSessionEvents(sessionId: sessionId);

Future<List<SessionRecoverySnapshot>> listRecoverableSessions() =>
    RustLib.instance.api.crateApiListRecoverableSessions();

Future<String> recoverSession({required SessionRecoverySnapshot snapshot}) =>
    RustLib.instance.api.crateApiRecoverSession(snapshot: snapshot);

/// Benchmark a model's realtime factor (seconds of audio transcribed per
/// second of wall-clock) using a 5s calibration chunk. Used by adaptive
/// HPT to decide whether a device can run q5 in a single pass.
/// Returns an error if the model cannot be loaded.
/// (No network access — purely local inference benchmark.)
Future<double> benchmarkRtf({required String modelPath}) =>
    RustLib.instance.api.crateApiBenchmarkRtf(modelPath: modelPath);

Future<List<ModelInfo>> listAvailableModels({required String modelsDir}) =>
    RustLib.instance.api.crateApiListAvailableModels(modelsDir: modelsDir);

Future<bool> isModelDownloaded({
  required String modelsDir,
  required String modelId,
}) => RustLib.instance.api.crateApiIsModelDownloaded(
  modelsDir: modelsDir,
  modelId: modelId,
);

Future<void> downloadModel({
  required String modelsDir,
  required String modelId,
}) => RustLib.instance.api.crateApiDownloadModel(
  modelsDir: modelsDir,
  modelId: modelId,
);

/// Poll the current download progress. Returns `None` if no download is
/// in progress or progress tracking has been reset.
Future<(BigInt, BigInt)?> getDownloadProgress() =>
    RustLib.instance.api.crateApiGetDownloadProgress();

Future<List<ExportedFile>> exportSession({
  required List<Segment> segments,
  required List<ExportFormat> formats,
  required String outputDir,
  required String title,
}) => RustLib.instance.api.crateApiExportSession(
  segments: segments,
  formats: formats,
  outputDir: outputDir,
  title: title,
);

/// Writes the raw mic/speaker audio captured during `session_id`'s live
/// recording as WAV files into the same session folder `export_session`
/// uses (blueprint §7.1: per-track mic.wav + speaker.wav). Call once, after
/// `stop_session` — the raw audio is only retained until the first call for
/// a given session. Returns an empty list (not an error) when there was no
/// live capture to save, e.g. a batch-file transcription.
Future<List<ExportedFile>> exportSessionAudio({
  required String sessionId,
  required String outputDir,
  required String title,
}) => RustLib.instance.api.crateApiExportSessionAudio(
  sessionId: sessionId,
  outputDir: outputDir,
  title: title,
);

/// Sanitize a candidate filename so it is safe to use on all target
/// filesystems (Windows/macOS/Linux). Falls back to "untitled" when the
/// input would otherwise be empty after stripping.
Future<String> exportSanitizeFilename({required String raw}) =>
    RustLib.instance.api.crateApiExportSanitizeFilename(raw: raw);

Future<AudioBuffer> decodeAudioFile({required String path}) =>
    RustLib.instance.api.crateApiDecodeAudioFile(path: path);

/// HPT file transcription: quick pass (base) then refine pass
/// (large-v3-turbo-q5) over the same decoded audio. UI shows
/// `quick_segments` immediately, then swaps in `refined_segments`
/// by key — target latency to first text: 3-5s.
Future<ProgressiveFileResult> progressiveTranscribeFile({
  required String quickModelPath,
  required String refineModelPath,
  required String path,
  String? language,
  required bool gpuEnabled,
  required int gpuDevice,
}) => RustLib.instance.api.crateApiProgressiveTranscribeFile(
  quickModelPath: quickModelPath,
  refineModelPath: refineModelPath,
  path: path,
  language: language,
  gpuEnabled: gpuEnabled,
  gpuDevice: gpuDevice,
);

Future<List<TranscribeFileResult>> transcribeFilesBatch({
  required String modelPath,
  required List<String> files,
  String? language,
  required bool gpuEnabled,
  required int gpuDevice,
}) => RustLib.instance.api.crateApiTranscribeFilesBatch(
  modelPath: modelPath,
  files: files,
  language: language,
  gpuEnabled: gpuEnabled,
  gpuDevice: gpuDevice,
);

Future<AppSettings> loadSettings() =>
    RustLib.instance.api.crateApiLoadSettings();

Future<void> saveSettings({required AppSettings settings}) =>
    RustLib.instance.api.crateApiSaveSettings(settings: settings);

/// Points the recorder at the app-support directory. Call once at startup
/// (right after `RustLib.init()`); creates the directory if missing.
Future<void> initFlightRecorder({required String appSupportDir}) => RustLib
    .instance
    .api
    .crateApiInitFlightRecorder(appSupportDir: appSupportDir);

Future<void> flightLogLifecycle({
  required String sessionId,
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiFlightLogLifecycle(
  sessionId: sessionId,
  from: from,
  to: to,
);

Future<void> flightLogSegmentBatch({
  required String sessionId,
  required BigInt batchSize,
  required BigInt totalSegments,
  required BigInt queueDepth,
}) => RustLib.instance.api.crateApiFlightLogSegmentBatch(
  sessionId: sessionId,
  batchSize: batchSize,
  totalSegments: totalSegments,
  queueDepth: queueDepth,
);

Future<void> flightLogError({
  required String sessionId,
  required String source,
  required String message,
}) => RustLib.instance.api.crateApiFlightLogError(
  sessionId: sessionId,
  source: source,
  message: message,
);

Future<void> flightLogAutoStop({
  required String sessionId,
  required BigInt minutes,
}) => RustLib.instance.api.crateApiFlightLogAutoStop(
  sessionId: sessionId,
  minutes: minutes,
);

Future<void> flightLogSystem({
  required String event,
  Map<String, String>? details,
}) => RustLib.instance.api.crateApiFlightLogSystem(
  event: event,
  details: details,
);

/// Reads the current flight-recorder contents (raw JSONL) for diagnostics.
Future<String> flightReadLog() => RustLib.instance.api.crateApiFlightReadLog();

Future<void> flightClearLog() => RustLib.instance.api.crateApiFlightClearLog();

Future<BigInt> flightEntryCount() =>
    RustLib.instance.api.crateApiFlightEntryCount();

Future<void> flightSetEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiFlightSetEnabled(enabled: enabled);

Future<bool> isAnotherInstanceRunning() =>
    RustLib.instance.api.crateApiIsAnotherInstanceRunning();

Future<void> acquireInstanceLock() =>
    RustLib.instance.api.crateApiAcquireInstanceLock();

Future<void> releaseInstanceLock() =>
    RustLib.instance.api.crateApiReleaseInstanceLock();

/// Result of an HPT (dual-model) file transcription: the quick pass from
/// `base` (`is_partial = true`) and the refined pass from
/// `large-v3-turbo-q5` (`is_partial = false`). Same segment order, same
/// `(source, timestamp)` keys — Dart replaces text by key.
class ProgressiveFileResult {
  final String filename;
  final List<Segment> quickSegments;
  final List<Segment> refinedSegments;
  final String language;

  const ProgressiveFileResult({
    required this.filename,
    required this.quickSegments,
    required this.refinedSegments,
    required this.language,
  });

  @override
  int get hashCode =>
      filename.hashCode ^
      quickSegments.hashCode ^
      refinedSegments.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressiveFileResult &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          quickSegments == other.quickSegments &&
          refinedSegments == other.refinedSegments &&
          language == other.language;
}
