// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'actions.dart';
import 'archive.dart';
import 'audio.dart';
import 'audio/device.dart';
import 'capabilities.dart';
import 'completion.dart';
import 'coverage.dart';
import 'disk.dart';
import 'doctor.dart';
import 'error.dart';
import 'export.dart';
import 'export/notulen.dart';
import 'frb_generated.dart';
import 'glossary.dart';
import 'mapreduce.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pdp.dart';
import 'pdp/audit.dart';
import 'pdp/redaction.dart';
import 'pdp/retention.dart';
import 'provenance.dart';
import 'session.dart';
import 'settings.dart';
import 'stt/file.dart';
import 'summary.dart';

// These functions are ignored because they are not marked as `pub`: `summarise_matches`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<Check>> runPreflightChecks() =>
    RustLib.instance.api.crateApiRunPreflightChecks();

Future<String> formatPreflightChecks({required List<Check> checks}) =>
    RustLib.instance.api.crateApiFormatPreflightChecks(checks: checks);

Future<GpuCapability> gpuCapability() =>
    RustLib.instance.api.crateApiGpuCapability();

/// Installs a `tracing` subscriber writing to stderr. Without this,
/// every `tracing::error!`/`warn!` call in the engine (session/pipeline
/// failures, capture errors, etc.) is silently dropped — there is no
/// default subscriber. Call once, right after `RustLib.init()`, before
/// anything else. Safe to call more than once (subsequent calls are a
/// harmless no-op via `try_init`).
Future<void> initLogging() => RustLib.instance.api.crateApiInitLogging();

Future<String> engineVersion() => RustLib.instance.api.crateApiEngineVersion();

Future<bool> healthCheck() => RustLib.instance.api.crateApiHealthCheck();

Future<List<AudioDeviceInfo>> listAudioDevices() =>
    RustLib.instance.api.crateApiListAudioDevices();

/// Playback devices — what the "Pengeras Suara" / loopback picker must show.
///
/// The speaker picker used to call [`list_audio_devices`], so it offered the
/// user a list of microphones to record the system audio from. On Linux this
/// resolves to PulseAudio/PipeWire *sinks* (same source of truth as
/// `audio::pulse`, which the loopback capture then turns into
/// `<sink>.monitor`), so what the picker shows and what gets recorded agree.
Future<List<AudioDeviceInfo>> listOutputAudioDevices() =>
    RustLib.instance.api.crateApiListOutputAudioDevices();

Future<String> startSession({required SessionConfig config}) =>
    RustLib.instance.api.crateApiStartSession(config: config);

Future<void> stopSession({required String sessionId}) =>
    RustLib.instance.api.crateApiStopSession(sessionId: sessionId);

Future<void> toggleMic({required String sessionId, required bool enabled}) =>
    RustLib.instance.api.crateApiToggleMic(
      sessionId: sessionId,
      enabled: enabled,
    );

Future<void> toggleSpeaker({
  required String sessionId,
  required bool enabled,
}) => RustLib.instance.api.crateApiToggleSpeaker(
  sessionId: sessionId,
  enabled: enabled,
);

Future<SessionStatus> getSessionStatus({required String sessionId}) =>
    RustLib.instance.api.crateApiGetSessionStatus(sessionId: sessionId);

Future<List<SessionEvent>> pollSessionEvents({required String sessionId}) =>
    RustLib.instance.api.crateApiPollSessionEvents(sessionId: sessionId);

/// Sessions left behind by a crash, with what is actually recoverable for
/// each (segment count, audio duration per source) rather than just the
/// configuration the old snapshot carried.
Future<List<RecoverableSession>> listRecoverableSessions() =>
    RustLib.instance.api.crateApiListRecoverableSessions();

/// Restores a crashed session: returns its recovered transcript along with
/// the live session id, and resumes capture into the same audio files.
Future<RecoveredSession> recoverSession({
  required SessionRecoverySnapshot snapshot,
}) => RustLib.instance.api.crateApiRecoverSession(snapshot: snapshot);

/// Discards one recoverable session and everything it held.
Future<void> deleteRecoverableSession({required String sessionId}) =>
    RustLib.instance.api.crateApiDeleteRecoverableSession(sessionId: sessionId);

/// Live capture health: how much audio each source has actually delivered,
/// whether it has ever been above the noise floor ("rekaman terkonfirmasi")
/// and how long it has been quiet. Drives both the recording indicator and
/// the integrity summary shown at Stop.
Future<CaptureHealth> getCaptureHealth({required String sessionId}) =>
    RustLib.instance.api.crateApiGetCaptureHealth(sessionId: sessionId);

/// Mirrors the user-entered title into the recovery snapshot, so a crashed
/// session appears in the recovery dialog under its name.
Future<void> setSessionTitle({
  required String sessionId,
  required String title,
}) => RustLib.instance.api.crateApiSetSessionTitle(
  sessionId: sessionId,
  title: title,
);

/// Free space on the volume holding `path`, plus whether that is enough to
/// keep recording. Called before a session starts and periodically while
/// one runs — three hours of "Rapat Online" is ~1.4 GB of WAV, and nothing
/// used to check.
Future<DiskSpaceStatus> checkDiskSpace({required String path}) =>
    RustLib.instance.api.crateApiCheckDiskSpace(path: path);

/// Benchmark a model's realtime factor (seconds of audio transcribed per
/// second of wall-clock) using a 5s calibration chunk. Used by adaptive
/// HPT to decide whether a device can run q5 in a single pass.
/// Returns an error if the model cannot be loaded.
/// (No network access — purely local inference benchmark.)
Future<double> benchmarkRtf({required String modelPath}) =>
    RustLib.instance.api.crateApiBenchmarkRtf(modelPath: modelPath);

Future<List<ModelInfo>> listAvailableModels({required String modelsDir}) =>
    RustLib.instance.api.crateApiListAvailableModels(modelsDir: modelsDir);

Future<bool> isModelDownloaded({
  required String modelsDir,
  required String modelId,
}) => RustLib.instance.api.crateApiIsModelDownloaded(
  modelsDir: modelsDir,
  modelId: modelId,
);

Future<void> downloadModel({
  required String modelsDir,
  required String modelId,
}) => RustLib.instance.api.crateApiDownloadModel(
  modelsDir: modelsDir,
  modelId: modelId,
);

/// Poll the current download progress. Returns `None` if no download is
/// in progress or progress tracking has been reset.
Future<(BigInt, BigInt)?> getDownloadProgress() =>
    RustLib.instance.api.crateApiGetDownloadProgress();

Future<List<ExportedFile>> exportSession({
  required List<Segment> segments,
  required List<ExportFormat> formats,
  required String outputDir,
  required String title,
}) => RustLib.instance.api.crateApiExportSession(
  segments: segments,
  formats: formats,
  outputDir: outputDir,
  title: title,
);

/// As [`export_session`], but leads the Markdown/TXT/HTML/DOCX output with
/// `summary` (Markdown, from [`generate_summary`]) and the meeting's
/// `bookmarks` as "Poin Penting". An empty `summary` with no bookmarks
/// produces byte-identical output to [`export_session`].
Future<List<ExportedFile>> exportSessionWithSummary({
  required List<Segment> segments,
  required List<ExportFormat> formats,
  required String outputDir,
  required String title,
  required String summary,
  required List<Bookmark> bookmarks,
}) => RustLib.instance.api.crateApiExportSessionWithSummary(
  segments: segments,
  formats: formats,
  outputDir: outputDir,
  title: title,
  summary: summary,
  bookmarks: bookmarks,
);

/// Writes the official "Notulen Rapat" DOCX into the session folder.
///
/// `form.variant` selects the layout ("Notulen Dinas" or "Notulen Ringkas").
/// The file is named `Notulen - <title>.docx` so it sits next to the
/// transcript exports without colliding with the plain DOCX transcript.
Future<ExportedFile> exportNotulen({
  required NotulenForm form,
  required List<Segment> segments,
  required String outputDir,
  required String title,
}) => RustLib.instance.api.crateApiExportNotulen(
  form: form,
  segments: segments,
  outputDir: outputDir,
  title: title,
);

/// Prefills a [`NotulenForm`]'s body sections from an AI summary: peserta,
/// pembahasan, keputusan and the tugas/PJ/tenggat rows. Pure and local — the
/// summary text is already in hand.
Future<NotulenDraft> notulenDraftFromSummary({required String summary}) =>
    RustLib.instance.api.crateApiNotulenDraftFromSummary(summary: summary);

/// Renders bookmarks as the `"[mm:ss] catatan"` lines the notulen's
/// "Poin Penting" section and every export use.
Future<List<String>> formatBookmarks({required List<Bookmark> bookmarks}) =>
    RustLib.instance.api.crateApiFormatBookmarks(bookmarks: bookmarks);

/// Writes the raw mic/speaker audio captured during `session_id`'s live
/// recording as WAV files into the same session folder `export_session`
/// uses (blueprint §7.1: per-track mic.wav + speaker.wav). Call once, after
/// `stop_session` — the raw audio is only retained until the first call for
/// a given session. Returns an empty list (not an error) when there was no
/// live capture to save, e.g. a batch-file transcription.
Future<List<ExportedFile>> exportSessionAudio({
  required String sessionId,
  required String outputDir,
  required String title,
}) => RustLib.instance.api.crateApiExportSessionAudio(
  sessionId: sessionId,
  outputDir: outputDir,
  title: title,
);

/// HPT file transcription: quick pass (base) then refine pass
/// (large-v3-turbo-q5) over the same decoded audio. UI shows
/// `quick_segments` immediately, then swaps in `refined_segments`
/// by key — target latency to first text: 3-5s.
Future<ProgressiveFileResult> progressiveTranscribeFile({
  required String quickModelPath,
  required String refineModelPath,
  required String path,
  String? language,
  required bool gpuEnabled,
  required int gpuDevice,
  required GlossaryConfig glossary,
  required int speakerHint,
}) => RustLib.instance.api.crateApiProgressiveTranscribeFile(
  quickModelPath: quickModelPath,
  refineModelPath: refineModelPath,
  path: path,
  language: language,
  gpuEnabled: gpuEnabled,
  gpuDevice: gpuDevice,
  glossary: glossary,
  speakerHint: speakerHint,
);

/// Transcribes every file in `files` against a single loaded model.
///
/// Loading the model is the expensive part (≈550 MB for large-v3-turbo-q5),
/// so callers should pass the whole queue in one call rather than looping
/// per file. Returns one outcome per input file, in input order, carrying
/// either the transcript or the error — so a single bad file no longer
/// disappears from the results without explanation.
/// `speaker_hint` is how many people are in the recordings, or `0` for
/// "work it out" (F10).
Future<List<BatchFileOutcome>> transcribeFilesBatch({
  required String modelPath,
  required List<String> files,
  String? language,
  required bool gpuEnabled,
  required int gpuDevice,
  required GlossaryConfig glossary,
  required int speakerHint,
}) => RustLib.instance.api.crateApiTranscribeFilesBatch(
  modelPath: modelPath,
  files: files,
  language: language,
  gpuEnabled: gpuEnabled,
  gpuDevice: gpuDevice,
  glossary: glossary,
  speakerHint: speakerHint,
);

/// Which file [`transcribe_files_batch`] is currently on. Poll this while the
/// batch future is in flight — that call only returns once *every* file is
/// done, so without it a long import shows a spinner that never moves.
Future<BatchProgressSnapshot?> getBatchProgress() =>
    RustLib.instance.api.crateApiGetBatchProgress();

/// Length of an audio file in seconds, from its header where possible.
///
/// Falls back to a full decode only when the container declares no frame
/// count, so the coverage check on save stays cheap for a 1.4 GB WAV.
Future<double> audioDurationSecs({required String path}) =>
    RustLib.instance.api.crateApiAudioDurationSecs(path: path);

/// What `segments` account for across a recording of `total_secs`, and
/// which stretches they miss. Pure; no decode, no inference.
Future<CoverageReport> transcriptCoverage({
  required List<Segment> segments,
  required double totalSecs,
}) => RustLib.instance.api.crateApiTranscriptCoverage(
  segments: segments,
  totalSecs: totalSecs,
);

/// [`transcript_coverage`] against the real length of `audio_path`.
Future<CoverageReport> transcriptCoverageForAudio({
  required List<Segment> segments,
  required String audioPath,
}) => RustLib.instance.api.crateApiTranscriptCoverageForAudio(
  segments: segments,
  audioPath: audioPath,
);

/// Folds `incoming` into `existing` by timestamp, keeping every existing
/// segment. Exposed so the UI can merge without re-running a pass.
Future<List<Segment>> mergeTranscriptSegments({
  required List<Segment> existing,
  required List<Segment> incoming,
}) => RustLib.instance.api.crateApiMergeTranscriptSegments(
  existing: existing,
  incoming: incoming,
);

/// Transcribes the stretches of `audio_path` that `existing` does not
/// cover, and returns the merged transcript.
///
/// `job_key` identifies this pass in [`read_completion_progress`] — the
/// session directory, in practice. Progress is published per source, so a
/// "Rapat Online" session's two tracks report independently.
///
/// Returns `existing` untouched (and `added = 0`) when the transcript
/// already covers the recording, or when the uncovered stretches hold no
/// speech — a meeting with ten silent minutes at the end is complete, and
/// must not sit at "Menyelesaikan transkrip…" forever.
Future<CompletionOutcome> completeSessionTranscript({
  required String modelPath,
  required String audioPath,
  required String jobKey,
  required List<Segment> existing,
  String? language,
  required bool gpuEnabled,
  required int gpuDevice,
  required GlossaryConfig glossary,
  required bool vadEnabled,
}) => RustLib.instance.api.crateApiCompleteSessionTranscript(
  modelPath: modelPath,
  audioPath: audioPath,
  jobKey: jobKey,
  existing: existing,
  language: language,
  gpuEnabled: gpuEnabled,
  gpuDevice: gpuDevice,
  glossary: glossary,
  vadEnabled: vadEnabled,
);

/// Per-source progress of every completion pass currently running.
Future<List<CompletionProgress>> readCompletionProgress() =>
    RustLib.instance.api.crateApiReadCompletionProgress();

/// Forgets one source's progress slot — used when a job is cancelled.
Future<void> clearCompletionProgress({
  required String jobKey,
  required String source,
}) => RustLib.instance.api.crateApiClearCompletionProgress(
  jobKey: jobKey,
  source: source,
);

/// Whether `text`, as a whole segment, is a caption Whisper invented over
/// silence rather than something a person said. Exposed so the UI can
/// explain a dropped line instead of silently removing it.
Future<bool> isNonSpeechText({required String text}) =>
    RustLib.instance.api.crateApiIsNonSpeechText(text: text);

/// Generates a Markdown meeting summary for `segments` using `config`.
///
/// Only the rendered transcript text is sent — no audio, no file paths, no
/// device names. Returns a `TranscribeError::Summary` (never a panic, never
/// a partial write) when the endpoint is unreachable or rejects the request,
/// so a failed summary can never look like a lost transcript.
Future<String> generateSummary({
  required List<Segment> segments,
  required SummaryConfig config,
  required List<Bookmark> bookmarks,
}) => RustLib.instance.api.crateApiGenerateSummary(
  segments: segments,
  config: config,
  bookmarks: bookmarks,
);

/// Summarises a meeting of any length, splitting it into time windows
/// and reducing when it does not fit one request (F15).
///
/// `progress` is polled from Dart via [`read_summary_progress`]; a
/// three-hour meeting is around eighteen round trips and the user has to
/// see which one is running.
Future<String> generateSummaryLong({
  required List<Segment> segments,
  required SummaryConfig config,
  required List<Bookmark> bookmarks,
}) => RustLib.instance.api.crateApiGenerateSummaryLong(
  segments: segments,
  config: config,
  bookmarks: bookmarks,
);

/// How far a map-reduce summary has got, or `None` when none is running.
Future<MapReduceProgress?> readSummaryProgress() =>
    RustLib.instance.api.crateApiReadSummaryProgress();

/// Pulls the tugas / PJ / tenggat / status rows out of a summary,
/// however the model formatted them. Pure and local.
Future<List<ActionItem>> parseActionItems({required String summary}) =>
    RustLib.instance.api.crateApiParseActionItems(summary: summary);

/// Removes the raw JSON block from a summary once it has been parsed, so
/// the rendered summary does not show the machine-readable copy under
/// the checklist.
Future<String> stripActionItemsBlock({required String summary}) =>
    RustLib.instance.api.crateApiStripActionItemsBlock(summary: summary);

/// RFC 5545 calendar for a checklist: one `VTODO` per task, plus a
/// `VEVENT` for each task whose deadline resolves to a date.
/// `today` is `YYYY-MM-DD`, used to resolve "Jumat" and "besok".
Future<String> actionItemsToIcs({
  required List<ActionItem> items,
  required String calendarName,
  required String today,
}) => RustLib.instance.api.crateApiActionItemsToIcs(
  items: items,
  calendarName: calendarName,
  today: today,
);

Future<String> actionItemsToCsv({required List<ActionItem> items}) =>
    RustLib.instance.api.crateApiActionItemsToCsv(items: items);

/// Indonesian label for a status, for the checklist's dropdown.
Future<String> actionStatusLabel({required ActionStatus status}) =>
    RustLib.instance.api.crateApiActionStatusLabel(status: status);

/// Splits a summary into lines and resolves each `[#n]` marker to a
/// transcript timestamp, dropping ids the transcript does not have.
Future<SummaryProvenance> parseSummaryProvenance({
  required String summary,
  required List<Segment> segments,
}) => RustLib.instance.api.crateApiParseSummaryProvenance(
  summary: summary,
  segments: segments,
);

/// [`parse_summary_provenance`] plus the stricter check: a citation whose
/// segment shares almost no vocabulary with the claim is dropped too.
Future<SummaryProvenance> parseSummaryProvenanceVerified({
  required String summary,
  required List<Segment> segments,
}) => RustLib.instance.api.crateApiParseSummaryProvenanceVerified(
  summary: summary,
  segments: segments,
);

/// The section headings a built-in template asks the model for — the starting
/// point when the user duplicates it into a template of their own (F8).
Future<List<String>> summaryTemplateHeadings({
  required SummaryTemplate template,
}) => RustLib.instance.api.crateApiSummaryTemplateHeadings(template: template);

/// Composes the instruction a user-authored template sends, from its free-text
/// instructions plus its declared section headings.
Future<String> composeSummaryInstruction({
  required String instructions,
  required List<String> headings,
}) => RustLib.instance.api.crateApiComposeSummaryInstruction(
  instructions: instructions,
  headings: headings,
);

/// Lists the models the configured summary endpoint offers, so the settings
/// UI can show a dropdown instead of a free-text field. Sends no transcript.
Future<List<String>> listSummaryModels({
  required SummaryProvider provider,
  required String baseUrl,
  required String apiKey,
}) => RustLib.instance.api.crateApiListSummaryModels(
  provider: provider,
  baseUrl: baseUrl,
  apiKey: apiKey,
);

/// Renders `segments` the way [`generate_summary`] would send them. Exposed
/// so the UI can show the user exactly what would be transmitted before they
/// opt in — no network access.
Future<String> summaryPreviewTranscript({required List<Segment> segments}) =>
    RustLib.instance.api.crateApiSummaryPreviewTranscript(segments: segments);

/// Previews the `initial_prompt` a glossary would produce. Pure and local.
Future<GlossaryPromptInfo> glossaryPromptPreview({
  required GlossaryConfig glossary,
  required String contextTail,
}) => RustLib.instance.api.crateApiGlossaryPromptPreview(
  glossary: glossary,
  contextTail: contextTail,
);

/// Parses an imported glossary file (`.txt` one-per-line, or `.csv`/TSV where
/// the first column is the term). Deduplicates case-insensitively.
Future<List<String>> parseGlossaryFile({required String content}) =>
    RustLib.instance.api.crateApiParseGlossaryFile(content: content);

/// Renders the glossary for export: `csv = true` produces a one-column CSV
/// with an `istilah` header, otherwise one term per line.
Future<String> renderGlossaryFile({
  required List<String> terms,
  required bool csv,
}) => RustLib.instance.api.crateApiRenderGlossaryFile(terms: terms, csv: csv);

/// Applies the conservative post-correction pass to arbitrary text. Exposed so
/// the UI can preview what the glossary would change before enabling it.
Future<String> applyGlossaryCorrections({
  required String text,
  required List<String> terms,
}) => RustLib.instance.api.crateApiApplyGlossaryCorrections(
  text: text,
  terms: terms,
);

/// Indexes one session, replacing whatever was indexed for it before.
/// Returns how many passages went in.
Future<int> archiveIndexSession({
  required String libraryPath,
  required String dirPath,
  required String title,
  required String date,
  required List<Segment> segments,
  required String summary,
  required BigInt transcriptSize,
  required PlatformInt64 transcriptMtimeMs,
}) => RustLib.instance.api.crateApiArchiveIndexSession(
  libraryPath: libraryPath,
  dirPath: dirPath,
  title: title,
  date: date,
  segments: segments,
  summary: summary,
  transcriptSize: transcriptSize,
  transcriptMtimeMs: transcriptMtimeMs,
);

/// Whether `dir_path`'s transcript has changed since it was indexed.
Future<bool> archiveIsStale({
  required String libraryPath,
  required String dirPath,
  required BigInt transcriptSize,
  required PlatformInt64 transcriptMtimeMs,
}) => RustLib.instance.api.crateApiArchiveIsStale(
  libraryPath: libraryPath,
  dirPath: dirPath,
  transcriptSize: transcriptSize,
  transcriptMtimeMs: transcriptMtimeMs,
);

/// Drops a session from the index — called when the user deletes it.
Future<void> archiveForgetSession({
  required String libraryPath,
  required String dirPath,
}) => RustLib.instance.api.crateApiArchiveForgetSession(
  libraryPath: libraryPath,
  dirPath: dirPath,
);

/// Ranked passages for `question`. Purely local; this is what the UI
/// can show before (or instead of) asking a model anything.
Future<List<ArchiveHit>> archiveSearch({
  required String libraryPath,
  required String question,
  required int limit,
}) => RustLib.instance.api.crateApiArchiveSearch(
  libraryPath: libraryPath,
  question: question,
  limit: limit,
);

Future<ArchiveStats> archiveStats({required String libraryPath}) =>
    RustLib.instance.api.crateApiArchiveStats(libraryPath: libraryPath);

Future<void> archiveClear({required String libraryPath}) =>
    RustLib.instance.api.crateApiArchiveClear(libraryPath: libraryPath);

/// Answers `question` from the archive.
///
/// Retrieval is local. The composed answer comes from the configured
/// summary endpoint, and **only the retrieved passages** are sent — not
/// the archive, not the audio, not the file paths. Returns the answer
/// alongside the passages it was allowed to use, so the UI can render
/// each `[K1]` as a link into the meeting it came from.
Future<ArchiveAnswer> archiveAsk({
  required String libraryPath,
  required String question,
  required SummaryConfig config,
}) => RustLib.instance.api.crateApiArchiveAsk(
  libraryPath: libraryPath,
  question: question,
  config: config,
);

/// What `config` would mask in `text`, with byte offsets so the UI can
/// highlight it before anything is changed.
Future<List<PiiMatch>> previewRedaction({
  required String text,
  required RedactionConfig config,
}) => RustLib.instance.api.crateApiPreviewRedaction(text: text, config: config);

/// `text` with every match replaced by its Indonesian placeholder.
Future<String> redactText({
  required String text,
  required RedactionConfig config,
}) => RustLib.instance.api.crateApiRedactText(text: text, config: config);

/// Everything `config` would mask across a whole transcript, for the
/// pre-export preview.
Future<List<PiiMatch>> previewRedactionSegments({
  required List<Segment> segments,
  required RedactionConfig config,
}) => RustLib.instance.api.crateApiPreviewRedactionSegments(
  segments: segments,
  config: config,
);

/// Returns a redacted **copy** of `segments`. The stored transcript is
/// never rewritten — a user who cannot get the original back has lost
/// evidence, not protected it.
Future<List<Segment>> redactSegments({
  required List<Segment> segments,
  required RedactionConfig config,
}) => RustLib.instance.api.crateApiRedactSegments(
  segments: segments,
  config: config,
);

/// Sessions in `library_path`, aged for the retention planner.
Future<List<SessionAge>> scanLibraryAges({required String libraryPath}) =>
    RustLib.instance.api.crateApiScanLibraryAges(libraryPath: libraryPath);

/// What `policy` would delete from `library_path` right now. Pure
/// preview: nothing is removed until [`apply_retention`] runs.
Future<RetentionPlan> previewRetention({
  required String libraryPath,
  required RetentionPolicy policy,
}) => RustLib.instance.api.crateApiPreviewRetention(
  libraryPath: libraryPath,
  policy: policy,
);

/// One Indonesian sentence describing a plan, for the confirm dialog.
Future<String> describeRetentionPlan({required RetentionPlan plan}) =>
    RustLib.instance.api.crateApiDescribeRetentionPlan(plan: plan);

/// Carries out a plan the user has confirmed, writing an audit entry per
/// deletion.
Future<RetentionOutcome> applyRetention({required RetentionPlan plan}) =>
    RustLib.instance.api.crateApiApplyRetention(plan: plan);

/// The audit log, newest first. `limit = 0` returns everything.
Future<List<AuditEntry>> readAuditLog({required int limit}) =>
    RustLib.instance.api.crateApiReadAuditLog(limit: limit);

Future<int> auditEntryCount() => RustLib.instance.api.crateApiAuditEntryCount();

/// Indonesian label for an audit action, so the viewer does not have to
/// keep its own copy of the mapping.
Future<String> auditActionLabel({required AuditAction action}) =>
    RustLib.instance.api.crateApiAuditActionLabel(action: action);

/// `YYYY-MM-DD HH:MM:SS` in local time.
Future<String> formatAuditTime({required BigInt atUnixMs}) =>
    RustLib.instance.api.crateApiFormatAuditTime(atUnixMs: atUnixMs);

/// Appends one entry. Called by the UI for acts only it knows about —
/// an export the user confirmed, a summary actually sent.
Future<void> writeAuditEntry({
  required AuditAction action,
  required String subject,
  required String destination,
  required String detail,
}) => RustLib.instance.api.crateApiWriteAuditEntry(
  action: action,
  subject: subject,
  destination: destination,
  detail: detail,
);

/// Writes the audit log to `destination` as CSV and records that it did.
Future<String> exportAuditLog({required String destination}) =>
    RustLib.instance.api.crateApiExportAuditLog(destination: destination);

/// The consent notice for a meeting, ready to paste into a meeting chat.
Future<String> consentNoticeText({
  required String template,
  required String title,
  required String date,
}) => RustLib.instance.api.crateApiConsentNoticeText(
  template: template,
  title: title,
  date: date,
);

/// The shipped default notice, for the settings field's placeholder.
Future<String> defaultConsentNotice() =>
    RustLib.instance.api.crateApiDefaultConsentNotice();

/// Records that the notice was delivered for this meeting.
Future<void> acknowledgeConsent({
  required String title,
  required String note,
}) => RustLib.instance.api.crateApiAcknowledgeConsent(title: title, note: note);

/// Every capability, where it runs, and whether it is on right now (F14).
///
/// Generated from `crate::capabilities`, which `crate::privacy`'s tests
/// check against the source — so this table cannot quietly disagree with
/// what the code does.
Future<List<Capability>> describeCapabilities({
  required AppSettings settings,
}) => RustLib.instance.api.crateApiDescribeCapabilities(settings: settings);

Future<AppSettings> loadSettings() =>
    RustLib.instance.api.crateApiLoadSettings();

Future<void> saveSettings({required AppSettings settings}) =>
    RustLib.instance.api.crateApiSaveSettings(settings: settings);

/// Points the recorder at the app-support directory. Call once at startup
/// (right after `RustLib.init()`); creates the directory if missing.
Future<void> initFlightRecorder({required String appSupportDir}) => RustLib
    .instance
    .api
    .crateApiInitFlightRecorder(appSupportDir: appSupportDir);

Future<void> flightLogLifecycle({
  required String sessionId,
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiFlightLogLifecycle(
  sessionId: sessionId,
  from: from,
  to: to,
);

Future<void> flightLogSegmentBatch({
  required String sessionId,
  required BigInt batchSize,
  required BigInt totalSegments,
  required BigInt queueDepth,
}) => RustLib.instance.api.crateApiFlightLogSegmentBatch(
  sessionId: sessionId,
  batchSize: batchSize,
  totalSegments: totalSegments,
  queueDepth: queueDepth,
);

Future<void> flightLogError({
  required String sessionId,
  required String source,
  required String message,
}) => RustLib.instance.api.crateApiFlightLogError(
  sessionId: sessionId,
  source: source,
  message: message,
);

Future<void> flightLogAutoStop({
  required String sessionId,
  required BigInt minutes,
}) => RustLib.instance.api.crateApiFlightLogAutoStop(
  sessionId: sessionId,
  minutes: minutes,
);

Future<void> flightLogSystem({
  required String event,
  Map<String, String>? details,
}) => RustLib.instance.api.crateApiFlightLogSystem(
  event: event,
  details: details,
);

/// Reads the current flight-recorder contents (raw JSONL) for diagnostics.
Future<String> flightReadLog() => RustLib.instance.api.crateApiFlightReadLog();

Future<void> flightClearLog() => RustLib.instance.api.crateApiFlightClearLog();

Future<BigInt> flightEntryCount() =>
    RustLib.instance.api.crateApiFlightEntryCount();

/// Packs "Ekspor Log Diagnostik": every rotated log generation plus the
/// preflight report, into `destination` as a `.zip`. Returns the path written.
///
/// Contains no transcript text and no audio — see
/// `flight_recorder::write_diagnostics_bundle` for the exhaustive contents.
Future<String> flightExportDiagnostics({
  required String destination,
  required String doctorReport,
  required String environment,
}) => RustLib.instance.api.crateApiFlightExportDiagnostics(
  destination: destination,
  doctorReport: doctorReport,
  environment: environment,
);

/// How many log files (active + rotated generations) the recorder currently
/// holds. Lets the diagnostics screen say what an export would contain.
Future<int> flightLogFileCount() =>
    RustLib.instance.api.crateApiFlightLogFileCount();

Future<void> flightSetEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiFlightSetEnabled(enabled: enabled);

Future<void> acquireInstanceLock() =>
    RustLib.instance.api.crateApiAcquireInstanceLock();

/// What the glossary actually contributes to one inference call.
///
/// `terms_used` / `terms_total` let Settings say "18 dari 40 istilah dipakai"
/// instead of silently discarding vocabulary: Whisper's prompt is capped at
/// 224 tokens and an over-long prompt degrades output, so the cap has to be
/// visible rather than a surprise. `u32` rather than `usize` so Dart sees an
/// `int` instead of a `BigInt`.
class GlossaryPromptInfo {
  /// The exact `initial_prompt` string that would be sent to Whisper.
  final String prompt;
  final int termsUsed;
  final int termsTotal;

  const GlossaryPromptInfo({
    required this.prompt,
    required this.termsUsed,
    required this.termsTotal,
  });

  @override
  int get hashCode =>
      prompt.hashCode ^ termsUsed.hashCode ^ termsTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlossaryPromptInfo &&
          runtimeType == other.runtimeType &&
          prompt == other.prompt &&
          termsUsed == other.termsUsed &&
          termsTotal == other.termsTotal;
}

/// What this *build* can actually do for GPU inference.
///
/// The Settings switch is a request, not a capability: whisper.cpp only
/// has a GPU backend if one was compiled in, so on a plain Linux build
/// turning "Akselerasi GPU" on changes nothing at all. The settings screen
/// used to claim "Transkripsi menggunakan GPU (Vulkan/CUDA/Metal)" purely
/// because the switch was on, which is a statement about the UI rather
/// than about the machine.
class GpuCapability {
  /// True when a GPU backend is compiled into this binary.
  final bool available;

  /// Human-facing backend name: "Vulkan", "CoreML", "Metal", "CPU".
  final String backend;

  const GpuCapability({required this.available, required this.backend});

  @override
  int get hashCode => available.hashCode ^ backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GpuCapability &&
          runtimeType == other.runtimeType &&
          available == other.available &&
          backend == other.backend;
}

/// Result of an HPT (dual-model) file transcription: the quick pass from
/// `base` (`is_partial = true`) and the refined pass from
/// `large-v3-turbo-q5` (`is_partial = false`). Same segment order, same
/// `(source, timestamp)` keys — Dart replaces text by key.
class ProgressiveFileResult {
  final String filename;
  final List<Segment> quickSegments;
  final List<Segment> refinedSegments;
  final String language;

  const ProgressiveFileResult({
    required this.filename,
    required this.quickSegments,
    required this.refinedSegments,
    required this.language,
  });

  @override
  int get hashCode =>
      filename.hashCode ^
      quickSegments.hashCode ^
      refinedSegments.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressiveFileResult &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          quickSegments == other.quickSegments &&
          refinedSegments == other.refinedSegments &&
          language == other.language;
}
