// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// An answer plus the passages it was allowed to use.
class ArchiveAnswer {
  final String answer;
  final List<ArchiveHit> sources;

  const ArchiveAnswer({required this.answer, required this.sources});

  @override
  int get hashCode => answer.hashCode ^ sources.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveAnswer &&
          runtimeType == other.runtimeType &&
          answer == other.answer &&
          sources == other.sources;
}

/// One indexed passage that matched.
class ArchiveHit {
  final String dirPath;
  final String title;

  /// `YYYY-MM-DD`.
  final String date;

  /// Seconds into the recording. `-1` for a summary passage, which has
  /// no single moment.
  final double timestamp;
  final String speaker;
  final String text;

  /// BM25 relevance; lower is better in SQLite's ranking, so this is
  /// negated to read the way a user expects.
  final double score;

  const ArchiveHit({
    required this.dirPath,
    required this.title,
    required this.date,
    required this.timestamp,
    required this.speaker,
    required this.text,
    required this.score,
  });

  @override
  int get hashCode =>
      dirPath.hashCode ^
      title.hashCode ^
      date.hashCode ^
      timestamp.hashCode ^
      speaker.hashCode ^
      text.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveHit &&
          runtimeType == other.runtimeType &&
          dirPath == other.dirPath &&
          title == other.title &&
          date == other.date &&
          timestamp == other.timestamp &&
          speaker == other.speaker &&
          text == other.text &&
          score == other.score;
}

/// What the index currently holds, for the settings screen.
class ArchiveStats {
  final int sessions;
  final int passages;
  final BigInt bytes;

  const ArchiveStats({
    required this.sessions,
    required this.passages,
    required this.bytes,
  });

  @override
  int get hashCode => sessions.hashCode ^ passages.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveStats &&
          runtimeType == other.runtimeType &&
          sessions == other.sessions &&
          passages == other.passages &&
          bytes == other.bytes;
}
