// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'glossary.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// User-chosen strategy for Hybrid Progressive Transcription (HPT).
///
/// * `Auto`      — benchmark q5; direct single-pass on fast devices,
///   dual-pass base→q5 on slow ones (default).
/// * `ForceDual` — always base quick → q5 refine (best for low-CPU devices
///   where the user wants instant partial text).
/// * `ForceDirect` — skip the base pass, run q5 alone from the start
///   (best for fast devices; lower total latency).
enum HptMode { auto, forceDual, forceDirect }

class SessionConfig {
  final bool micEnabled;
  final bool speakerEnabled;
  final SessionMode mode;
  final String? micDeviceId;
  final String? speakerDeviceId;
  final String modelPath;

  /// Optional second model for Hybrid Progressive Transcription (HPT).
  /// When `Some`, each source runs quick (base) → refine (q5) so text
  /// renders in 3-5s and is then replaced in place by the accurate pass.
  /// `None` = classic single-model live transcription.
  final String? refineModelPath;

  /// Overrides adaptive HPT routing. `Auto` benchmarks live; the other
  /// variants force a specific path regardless of device capability.
  final HptMode hptMode;

  /// Gate Whisper inference on the dual-stage VAD. `false` transcribes
  /// every buffered chunk — more CPU, but nothing can be dropped by a
  /// mis-tuned speech detector. Honoured by `pipeline::LivePipeline`.
  final bool vadEnabled;

  /// Enable GPU acceleration for whisper inference (Vulkan/CUDA/Metal).
  /// Mirrors `AppSettings::gpu_enabled`; the caller is responsible for
  /// copying the user's setting in when building this config.
  final bool gpuEnabled;

  /// GPU device index to use when `gpu_enabled` is true (0 = default).
  final int gpuDevice;

  /// Stream captured audio to disk as it arrives instead of holding it
  /// in RAM until Stop. On by default; the switch exists because this
  /// touches the capture path that was only just stabilised, so a
  /// release can fall back without a rebuild. `session` keeps a bounded
  /// RAM buffer as the fallback either way.
  final bool audioToDisk;

  /// Kamus istilah for this session: the global list plus whatever the
  /// notulis added for this meeting. Fed to Whisper's `initial_prompt` and,
  /// when `post_correction` is set, used to repair near-misses in the
  /// output. Defaults to empty, which is a no-op.
  final GlossaryConfig glossary;

  /// Fastest model installed on this machine (`tiny`/`base`), used for
  /// the *live preview only* when `model_path` turns out to be slower
  /// than real time on this device.
  ///
  /// This does not downgrade the transcript the user ends up with: the
  /// post-stop completion pass re-runs the saved audio with `model_path`
  /// afterwards. What it prevents is the live worker falling further
  /// behind every minute until Stop, which on the device this was
  /// measured on produced a 6-minute recording with 8 seconds of
  /// transcript. `None` disables the substitution.
  final String? fallbackModelPath;

  /// Per-session language override (Sprint 14a item 11): `Some("id")` /
  /// `Some("en")` forces that language for this session only; `Some`
  /// with any other value or `None` means "no override, decide from
  /// `AppSettings::language` and `mode`" (see
  /// `session::effective_session_language`). Distinct from the global
  /// `AppSettings::language` persisted on disk — this lets one meeting
  /// in a mostly-Indonesian install be transcribed in English (or vice
  /// versa) without changing every future session's default.
  final String? language;

  const SessionConfig({
    required this.micEnabled,
    required this.speakerEnabled,
    required this.mode,
    this.micDeviceId,
    this.speakerDeviceId,
    required this.modelPath,
    this.refineModelPath,
    required this.hptMode,
    required this.vadEnabled,
    required this.gpuEnabled,
    required this.gpuDevice,
    required this.audioToDisk,
    required this.glossary,
    this.fallbackModelPath,
    this.language,
  });

  @override
  int get hashCode =>
      micEnabled.hashCode ^
      speakerEnabled.hashCode ^
      mode.hashCode ^
      micDeviceId.hashCode ^
      speakerDeviceId.hashCode ^
      modelPath.hashCode ^
      refineModelPath.hashCode ^
      hptMode.hashCode ^
      vadEnabled.hashCode ^
      gpuEnabled.hashCode ^
      gpuDevice.hashCode ^
      audioToDisk.hashCode ^
      glossary.hashCode ^
      fallbackModelPath.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionConfig &&
          runtimeType == other.runtimeType &&
          micEnabled == other.micEnabled &&
          speakerEnabled == other.speakerEnabled &&
          mode == other.mode &&
          micDeviceId == other.micDeviceId &&
          speakerDeviceId == other.speakerDeviceId &&
          modelPath == other.modelPath &&
          refineModelPath == other.refineModelPath &&
          hptMode == other.hptMode &&
          vadEnabled == other.vadEnabled &&
          gpuEnabled == other.gpuEnabled &&
          gpuDevice == other.gpuDevice &&
          audioToDisk == other.audioToDisk &&
          glossary == other.glossary &&
          fallbackModelPath == other.fallbackModelPath &&
          language == other.language;
}

enum SessionMode { webinar, online, offline }
