// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

/// User-chosen strategy for Hybrid Progressive Transcription (HPT).
///
/// * `Auto`      — benchmark q5; direct single-pass on fast devices,
///   dual-pass base→q5 on slow ones (default).
/// * `ForceDual` — always base quick → q5 refine (best for low-CPU devices
///   where the user wants instant partial text).
/// * `ForceDirect` — skip the base pass, run q5 alone from the start
///   (best for fast devices; lower total latency).
enum HptMode {
  auto,
  forceDual,
  forceDirect;

  static Future<HptMode> default_() =>
      RustLib.instance.api.crateAudioHptModeDefault();
}

class SessionConfig {
  final bool micEnabled;
  final bool speakerEnabled;
  final SessionMode mode;
  final String? micDeviceId;
  final String? speakerDeviceId;
  final String modelPath;

  /// Optional second model for Hybrid Progressive Transcription (HPT).
  /// When `Some`, each source runs quick (base) → refine (q5) so text
  /// renders in 3-5s and is then replaced in place by the accurate pass.
  /// `None` = classic single-model live transcription.
  final String? refineModelPath;

  /// Overrides adaptive HPT routing. `Auto` benchmarks live; the other
  /// variants force a specific path regardless of device capability.
  final HptMode hptMode;
  final bool vadEnabled;
  final int sampleRate;
  final int chunkDurationSecs;

  /// Enable GPU acceleration for whisper inference (Vulkan/CUDA/Metal).
  /// Mirrors `AppSettings::gpu_enabled`; the caller is responsible for
  /// copying the user's setting in when building this config.
  final bool gpuEnabled;

  /// GPU device index to use when `gpu_enabled` is true (0 = default).
  final int gpuDevice;

  const SessionConfig({
    required this.micEnabled,
    required this.speakerEnabled,
    required this.mode,
    this.micDeviceId,
    this.speakerDeviceId,
    required this.modelPath,
    this.refineModelPath,
    required this.hptMode,
    required this.vadEnabled,
    required this.sampleRate,
    required this.chunkDurationSecs,
    required this.gpuEnabled,
    required this.gpuDevice,
  });

  static Future<SessionConfig> forMode({
    required SessionMode mode,
    required String modelPath,
  }) => RustLib.instance.api.crateAudioSessionConfigForMode(
    mode: mode,
    modelPath: modelPath,
  );

  /// True when HPT is configured (refine model present and distinct from
  /// the quick model).
  Future<bool> hptEnabled() =>
      RustLib.instance.api.crateAudioSessionConfigHptEnabled(that: this);

  @override
  int get hashCode =>
      micEnabled.hashCode ^
      speakerEnabled.hashCode ^
      mode.hashCode ^
      micDeviceId.hashCode ^
      speakerDeviceId.hashCode ^
      modelPath.hashCode ^
      refineModelPath.hashCode ^
      hptMode.hashCode ^
      vadEnabled.hashCode ^
      sampleRate.hashCode ^
      chunkDurationSecs.hashCode ^
      gpuEnabled.hashCode ^
      gpuDevice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionConfig &&
          runtimeType == other.runtimeType &&
          micEnabled == other.micEnabled &&
          speakerEnabled == other.speakerEnabled &&
          mode == other.mode &&
          micDeviceId == other.micDeviceId &&
          speakerDeviceId == other.speakerDeviceId &&
          modelPath == other.modelPath &&
          refineModelPath == other.refineModelPath &&
          hptMode == other.hptMode &&
          vadEnabled == other.vadEnabled &&
          sampleRate == other.sampleRate &&
          chunkDurationSecs == other.chunkDurationSecs &&
          gpuEnabled == other.gpuEnabled &&
          gpuDevice == other.gpuDevice;
}

enum SessionMode {
  webinar,
  online,
  offline;

  Future<(bool, bool)> defaultToggles() =>
      RustLib.instance.api.crateAudioSessionModeDefaultToggles(that: this);

  Future<bool> echoDedupeEnabled() =>
      RustLib.instance.api.crateAudioSessionModeEchoDedupeEnabled(that: this);
}
