// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One row of the table.
class Capability {
  /// Stable key, for tests and for the UI's list keys.
  final String id;

  /// Indonesian name, as the feature is called in the UI.
  final String name;

  /// One sentence on what it does, in Indonesian.
  final String detail;
  final RunsAt runsAt;

  /// Rendered destination: "Lokal", the configured endpoint, or a host.
  final String whereLabel;

  /// Whether it would do anything right now, given the settings.
  final bool enabled;

  /// Why it is off, when it is. Empty when enabled.
  final String disabledReason;

  /// The Rust module that implements it, relative to `rust_core/src`.
  ///
  /// This is the field that makes the table checkable rather than
  /// decorative: `privacy.rs` scans exactly these files.
  final String module;

  const Capability({
    required this.id,
    required this.name,
    required this.detail,
    required this.runsAt,
    required this.whereLabel,
    required this.enabled,
    required this.disabledReason,
    required this.module,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      detail.hashCode ^
      runsAt.hashCode ^
      whereLabel.hashCode ^
      enabled.hashCode ^
      disabledReason.hashCode ^
      module.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Capability &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          detail == other.detail &&
          runsAt == other.runsAt &&
          whereLabel == other.whereLabel &&
          enabled == other.enabled &&
          disabledReason == other.disabledReason &&
          module == other.module;
}

/// Where a capability's work happens.
enum RunsAt {
  /// Entirely on this machine. Nothing is sent anywhere.
  local,

  /// The user-configured summary endpoint, and nothing else.
  summaryEndpoint,

  /// A fixed third party, named in [`Capability::where_label`].
  internet,
}
