// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'coverage.dart';
import 'export.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What a completion pass did.
class CompletionOutcome {
  /// The whole transcript, existing plus recovered, in time order.
  final List<Segment> segments;

  /// How many segments the pass added.
  final int added;

  /// How many hallucinated/non-speech lines it refused to add.
  final int rejected;

  /// Coverage after the merge, in wall-clock terms, with gaps that hold
  /// no speech already removed — those cannot be closed by transcribing
  /// them and must not leave a session marked unfinished forever.
  final CoverageReport coverage;

  /// Seconds of `audio_path` the VAD found speech in.
  final double speechSecs;

  /// How much of that speech the merged transcript now covers. This is
  /// the honest completeness figure for a recording that is mostly
  /// silence, which a three-hour meeting with one speaker usually is.
  final double speechCoveredSecs;

  /// Length of the audio file the pass worked from.
  final double audioSecs;

  const CompletionOutcome({
    required this.segments,
    required this.added,
    required this.rejected,
    required this.coverage,
    required this.speechSecs,
    required this.speechCoveredSecs,
    required this.audioSecs,
  });

  @override
  int get hashCode =>
      segments.hashCode ^
      added.hashCode ^
      rejected.hashCode ^
      coverage.hashCode ^
      speechSecs.hashCode ^
      speechCoveredSecs.hashCode ^
      audioSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompletionOutcome &&
          runtimeType == other.runtimeType &&
          segments == other.segments &&
          added == other.added &&
          rejected == other.rejected &&
          coverage == other.coverage &&
          speechSecs == other.speechSecs &&
          speechCoveredSecs == other.speechCoveredSecs &&
          audioSecs == other.audioSecs;
}

/// One source's completion pass, as the UI sees it.
class CompletionProgress {
  /// Opaque key the caller chose — the session directory, in practice.
  final String jobKey;
  final String source;

  /// `0.0..=1.0` over the speech that needed transcribing.
  final double fraction;
  final double etaSecs;
  final bool done;

  const CompletionProgress({
    required this.jobKey,
    required this.source,
    required this.fraction,
    required this.etaSecs,
    required this.done,
  });

  @override
  int get hashCode =>
      jobKey.hashCode ^
      source.hashCode ^
      fraction.hashCode ^
      etaSecs.hashCode ^
      done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompletionProgress &&
          runtimeType == other.runtimeType &&
          jobKey == other.jobKey &&
          source == other.source &&
          fraction == other.fraction &&
          etaSecs == other.etaSecs &&
          done == other.done;
}
