// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What a transcript accounts for, and what it misses.
class CoverageReport {
  /// Seconds of the recording covered by at least one segment.
  final double coveredSecs;

  /// Length of the recording.
  final double totalSecs;

  /// `covered_secs / total_secs`, clamped to `0.0..=1.0`. `1.0` when the
  /// recording has no length (nothing can be missing from nothing).
  final double fraction;

  /// Stretches with no segment over them, longest-lived first in time
  /// order. Only gaps of at least `min_gap_secs` are reported.
  final List<TimeRange> gaps;

  /// `gaps` summed.
  final double missingSecs;

  const CoverageReport({
    required this.coveredSecs,
    required this.totalSecs,
    required this.fraction,
    required this.gaps,
    required this.missingSecs,
  });

  @override
  int get hashCode =>
      coveredSecs.hashCode ^
      totalSecs.hashCode ^
      fraction.hashCode ^
      gaps.hashCode ^
      missingSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoverageReport &&
          runtimeType == other.runtimeType &&
          coveredSecs == other.coveredSecs &&
          totalSecs == other.totalSecs &&
          fraction == other.fraction &&
          gaps == other.gaps &&
          missingSecs == other.missingSecs;
}

/// A half-open span of the recording, in seconds from its start.
class TimeRange {
  final double start;
  final double end;

  const TimeRange({required this.start, required this.end});

  @override
  int get hashCode => start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeRange &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end;
}
