// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_as_mono`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `decode_audio_file`, `resample_to_target`

/// Decoded audio, resampled to mono f32 PCM at [`TARGET_SAMPLE_RATE`].
class AudioBuffer {
  final Float32List samples;
  final int originalSampleRate;
  final int originalChannels;
  final double durationSecs;

  const AudioBuffer({
    required this.samples,
    required this.originalSampleRate,
    required this.originalChannels,
    required this.durationSecs,
  });

  @override
  int get hashCode =>
      samples.hashCode ^
      originalSampleRate.hashCode ^
      originalChannels.hashCode ^
      durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioBuffer &&
          runtimeType == other.runtimeType &&
          samples == other.samples &&
          originalSampleRate == other.originalSampleRate &&
          originalChannels == other.originalChannels &&
          durationSecs == other.durationSecs;
}
