// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

enum DiskSpaceLevel {
  ok,

  /// Keep going, but say something.
  low,

  /// Stop cleanly now, while saving still works.
  critical,
}

/// Free space on the volume holding `path`, plus what to do about it.
class DiskSpaceStatus {
  /// `None` when the volume could not be identified — treated as `Ok`
  /// rather than blocking a recording on a failed measurement.
  final BigInt? availableBytes;
  final DiskSpaceLevel level;

  /// Ready-to-show Indonesian text, empty when `level` is `Ok`.
  final String message;

  const DiskSpaceStatus({
    this.availableBytes,
    required this.level,
    required this.message,
  });

  @override
  int get hashCode =>
      availableBytes.hashCode ^ level.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiskSpaceStatus &&
          runtimeType == other.runtimeType &&
          availableBytes == other.availableBytes &&
          level == other.level &&
          message == other.message;
}
