// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'doctor.freezed.dart';

/// One diagnostic check result with a human-readable remediation hint.
class Check {
  final String name;
  final CheckStatus status;
  final String? remediation;

  const Check({required this.name, required this.status, this.remediation});

  @override
  int get hashCode => name.hashCode ^ status.hashCode ^ remediation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Check &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          status == other.status &&
          remediation == other.remediation;
}

@freezed
sealed class CheckStatus with _$CheckStatus {
  const CheckStatus._();

  const factory CheckStatus.ok() = CheckStatus_Ok;
  const factory CheckStatus.warn(String field0) = CheckStatus_Warn;
  const factory CheckStatus.fail(String field0) = CheckStatus_Fail;
}
