// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`

@freezed
sealed class TranscribeError with _$TranscribeError implements FrbException {
  const TranscribeError._();

  const factory TranscribeError.audioDevice(String field0) =
      TranscribeError_AudioDevice;
  const factory TranscribeError.audioDecode(String field0) =
      TranscribeError_AudioDecode;
  const factory TranscribeError.model(String field0) = TranscribeError_Model;
  const factory TranscribeError.transcription(String field0) =
      TranscribeError_Transcription;
  const factory TranscribeError.export_(String field0) = TranscribeError_Export;

  /// String, not `std::io::Error` — the latter has no FRB `SseEncode`
  /// impl, which broke bridge codegen. Construct via
  /// `TranscribeError::from(io_err)` or `.map_err(TranscribeError::from)`.
  const factory TranscribeError.io(String field0) = TranscribeError_Io;
  const factory TranscribeError.invalidInput(String field0) =
      TranscribeError_InvalidInput;
  const factory TranscribeError.sessionNotFound(String field0) =
      TranscribeError_SessionNotFound;
}
