// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `atomic_write`, `fmt_srt_time`, `fmt_timestamp`, `fmt_vtt_time`, `html_escape`, `run_on_stop_hook`, `to_docx_bytes`, `to_html`, `to_markdown`, `to_srt`, `to_txt`, `to_vtt`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WordTimestamp`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `export_segments`, `export_session_audio`, `session_dir_for`, `write_wav`

/// Sanitize a user/window-title-derived name into a safe path component:
/// no separators, no traversal, no control characters.
Future<String> sanitizeFilename({required String raw}) =>
    RustLib.instance.api.crateExportSanitizeFilename(raw: raw);

enum ExportFormat { markdown, txt, json, srt, vtt, html, docx }

class ExportedFile {
  final String filename;
  final String path;
  final BigInt sizeBytes;

  const ExportedFile({
    required this.filename,
    required this.path,
    required this.sizeBytes,
  });

  @override
  int get hashCode => filename.hashCode ^ path.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportedFile &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          path == other.path &&
          sizeBytes == other.sizeBytes;
}

class Segment {
  final String source;
  final String speaker;
  final String text;
  final double timestamp;
  final double duration;
  final String language;
  final double confidence;
  final bool isPartial;
  final bool lowConfidence;

  const Segment({
    required this.source,
    required this.speaker,
    required this.text,
    required this.timestamp,
    required this.duration,
    required this.language,
    required this.confidence,
    required this.isPartial,
    required this.lowConfidence,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      speaker.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      duration.hashCode ^
      language.hashCode ^
      confidence.hashCode ^
      isPartial.hashCode ^
      lowConfidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Segment &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          speaker == other.speaker &&
          text == other.text &&
          timestamp == other.timestamp &&
          duration == other.duration &&
          language == other.language &&
          confidence == other.confidence &&
          isPartial == other.isPartial &&
          lowConfidence == other.lowConfidence;
}
