// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A marker the notulis dropped during the meeting (F9).
///
/// One keystroke during a three-hour rapat is the workflow this replaces:
/// before this existed, flagging "this is the decision" meant writing the
/// wall-clock time on paper.
class Bookmark {
  /// Offset into the recording, in seconds.
  final double timestamp;

  /// Optional one-line note. Empty is normal — the timestamp is the point.
  final String note;

  const Bookmark({required this.timestamp, required this.note});

  @override
  int get hashCode => timestamp.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bookmark &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          note == other.note;
}

enum ExportFormat {
  markdown,
  txt,
  json,
  srt,
  vtt,
  html,
  docx,

  /// Transcript as a spreadsheet, one row per final segment (F19).
  csv,

  /// Paginated document with the font embedded, so it reads the same on
  /// a machine that has never seen this app (F19).
  pdf,
}

class ExportedFile {
  final String filename;
  final String path;
  final BigInt sizeBytes;

  const ExportedFile({
    required this.filename,
    required this.path,
    required this.sizeBytes,
  });

  @override
  int get hashCode => filename.hashCode ^ path.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportedFile &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          path == other.path &&
          sizeBytes == other.sizeBytes;
}

class Segment {
  final String source;
  final String speaker;
  final String text;
  final double timestamp;
  final double duration;
  final String language;
  final double confidence;

  /// Average log probability per token from Whisper (negative, e.g. -0.5).
  /// Used by confidence.rs to flag low-quality segments.
  final double avgLogProb;
  final bool isPartial;
  final bool lowConfidence;

  /// Per-word spans from whisper's token timestamps, aggregated by
  /// [`crate::stt::words`]. Empty when the segment was produced without
  /// word timestamps (every transcript written before Sprint 4b, and the
  /// live preview's uncommitted tail), which is why it is
  /// `#[serde(default)]`: an old `transcript.json` must still load.
  final List<WordTimestamp> words;

  const Segment({
    required this.source,
    required this.speaker,
    required this.text,
    required this.timestamp,
    required this.duration,
    required this.language,
    required this.confidence,
    required this.avgLogProb,
    required this.isPartial,
    required this.lowConfidence,
    required this.words,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      speaker.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      duration.hashCode ^
      language.hashCode ^
      confidence.hashCode ^
      avgLogProb.hashCode ^
      isPartial.hashCode ^
      lowConfidence.hashCode ^
      words.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Segment &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          speaker == other.speaker &&
          text == other.text &&
          timestamp == other.timestamp &&
          duration == other.duration &&
          language == other.language &&
          confidence == other.confidence &&
          avgLogProb == other.avgLogProb &&
          isPartial == other.isPartial &&
          lowConfidence == other.lowConfidence &&
          words == other.words;
}

/// One word of a segment, with the span the player highlights and the
/// probability the "Tinjau" filter underlines on.
class WordTimestamp {
  final String word;
  final double start;
  final double end;

  /// Mean of the probabilities whisper gave this word's tokens, in
  /// `0.0..=1.0`. `0.0` means "not measured" (an interpolated word), not
  /// "certainly wrong" — see [`crate::stt::words::interpolate_words`].
  final double prob;

  const WordTimestamp({
    required this.word,
    required this.start,
    required this.end,
    required this.prob,
  });

  @override
  int get hashCode =>
      word.hashCode ^ start.hashCode ^ end.hashCode ^ prob.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordTimestamp &&
          runtimeType == other.runtimeType &&
          word == other.word &&
          start == other.start &&
          end == other.end &&
          prob == other.prob;
}
