// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A marker the notulis dropped during the meeting (F9).
///
/// One keystroke during a three-hour rapat is the workflow this replaces:
/// before this existed, flagging "this is the decision" meant writing the
/// wall-clock time on paper.
class Bookmark {
  /// Offset into the recording, in seconds.
  final double timestamp;

  /// Optional one-line note. Empty is normal — the timestamp is the point.
  final String note;

  const Bookmark({required this.timestamp, required this.note});

  @override
  int get hashCode => timestamp.hashCode ^ note.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bookmark &&
          runtimeType == other.runtimeType &&
          timestamp == other.timestamp &&
          note == other.note;
}

enum ExportFormat { markdown, txt, json, srt, vtt, html, docx }

class ExportedFile {
  final String filename;
  final String path;
  final BigInt sizeBytes;

  const ExportedFile({
    required this.filename,
    required this.path,
    required this.sizeBytes,
  });

  @override
  int get hashCode => filename.hashCode ^ path.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportedFile &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          path == other.path &&
          sizeBytes == other.sizeBytes;
}

class Segment {
  final String source;
  final String speaker;
  final String text;
  final double timestamp;
  final double duration;
  final String language;
  final double confidence;

  /// Average log probability per token from Whisper (negative, e.g. -0.5).
  /// Used by confidence.rs to flag low-quality segments.
  final double avgLogProb;
  final bool isPartial;
  final bool lowConfidence;

  const Segment({
    required this.source,
    required this.speaker,
    required this.text,
    required this.timestamp,
    required this.duration,
    required this.language,
    required this.confidence,
    required this.avgLogProb,
    required this.isPartial,
    required this.lowConfidence,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      speaker.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      duration.hashCode ^
      language.hashCode ^
      confidence.hashCode ^
      avgLogProb.hashCode ^
      isPartial.hashCode ^
      lowConfidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Segment &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          speaker == other.speaker &&
          text == other.text &&
          timestamp == other.timestamp &&
          duration == other.duration &&
          language == other.language &&
          confidence == other.confidence &&
          avgLogProb == other.avgLogProb &&
          isPartial == other.isPartial &&
          lowConfidence == other.lowConfidence;
}
