// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'audio.dart';
import 'audio/device.dart';
import 'completion.dart';
import 'coverage.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'disk.dart';
import 'doctor.dart';
import 'error.dart';
import 'export.dart';
import 'export/notulen.dart';
import 'frb_generated.dart';
import 'glossary.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'pdp.dart';
import 'pdp/audit.dart';
import 'pdp/redaction.dart';
import 'pdp/retention.dart';
import 'session.dart';
import 'settings.dart';
import 'stt/file.dart';
import 'summary.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  AudioDeviceInfo dco_decode_audio_device_info(dynamic raw);

  @protected
  AuditAction dco_decode_audit_action(dynamic raw);

  @protected
  AuditEntry dco_decode_audit_entry(dynamic raw);

  @protected
  BatchFileOutcome dco_decode_batch_file_outcome(dynamic raw);

  @protected
  BatchFileStatus dco_decode_batch_file_status(dynamic raw);

  @protected
  BatchProgressSnapshot dco_decode_batch_progress_snapshot(dynamic raw);

  @protected
  Bookmark dco_decode_bookmark(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  BatchProgressSnapshot dco_decode_box_autoadd_batch_progress_snapshot(
    dynamic raw,
  );

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  GlossaryConfig dco_decode_box_autoadd_glossary_config(dynamic raw);

  @protected
  NotulenForm dco_decode_box_autoadd_notulen_form(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_box_autoadd_record_u_64_u_64(dynamic raw);

  @protected
  RedactionConfig dco_decode_box_autoadd_redaction_config(dynamic raw);

  @protected
  RetentionPlan dco_decode_box_autoadd_retention_plan(dynamic raw);

  @protected
  RetentionPolicy dco_decode_box_autoadd_retention_policy(dynamic raw);

  @protected
  Segment dco_decode_box_autoadd_segment(dynamic raw);

  @protected
  SessionConfig dco_decode_box_autoadd_session_config(dynamic raw);

  @protected
  SessionRecoverySnapshot dco_decode_box_autoadd_session_recovery_snapshot(
    dynamic raw,
  );

  @protected
  SummaryConfig dco_decode_box_autoadd_summary_config(dynamic raw);

  @protected
  TranscribeFileResult dco_decode_box_autoadd_transcribe_file_result(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CaptureHealth dco_decode_capture_health(dynamic raw);

  @protected
  ChannelCapture dco_decode_channel_capture(dynamic raw);

  @protected
  ChannelCounters dco_decode_channel_counters(dynamic raw);

  @protected
  Check dco_decode_check(dynamic raw);

  @protected
  CheckStatus dco_decode_check_status(dynamic raw);

  @protected
  CompletionOutcome dco_decode_completion_outcome(dynamic raw);

  @protected
  CompletionProgress dco_decode_completion_progress(dynamic raw);

  @protected
  CoverageReport dco_decode_coverage_report(dynamic raw);

  @protected
  CustomSummaryTemplate dco_decode_custom_summary_template(dynamic raw);

  @protected
  DiskSpaceLevel dco_decode_disk_space_level(dynamic raw);

  @protected
  DiskSpaceStatus dco_decode_disk_space_status(dynamic raw);

  @protected
  ExportFormat dco_decode_export_format(dynamic raw);

  @protected
  ExportedFile dco_decode_exported_file(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GlossaryConfig dco_decode_glossary_config(dynamic raw);

  @protected
  GlossaryPromptInfo dco_decode_glossary_prompt_info(dynamic raw);

  @protected
  GlossarySettings dco_decode_glossary_settings(dynamic raw);

  @protected
  GpuCapability dco_decode_gpu_capability(dynamic raw);

  @protected
  HptMode dco_decode_hpt_mode(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AudioDeviceInfo> dco_decode_list_audio_device_info(dynamic raw);

  @protected
  List<AuditEntry> dco_decode_list_audit_entry(dynamic raw);

  @protected
  List<BatchFileOutcome> dco_decode_list_batch_file_outcome(dynamic raw);

  @protected
  List<Bookmark> dco_decode_list_bookmark(dynamic raw);

  @protected
  List<ChannelCapture> dco_decode_list_channel_capture(dynamic raw);

  @protected
  List<Check> dco_decode_list_check(dynamic raw);

  @protected
  List<CompletionProgress> dco_decode_list_completion_progress(dynamic raw);

  @protected
  List<CustomSummaryTemplate> dco_decode_list_custom_summary_template(
    dynamic raw,
  );

  @protected
  List<ExportFormat> dco_decode_list_export_format(dynamic raw);

  @protected
  List<ExportedFile> dco_decode_list_exported_file(dynamic raw);

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw);

  @protected
  List<PiiMatch> dco_decode_list_pii_match(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<RecoverableSession> dco_decode_list_recoverable_session(dynamic raw);

  @protected
  List<RetentionItem> dco_decode_list_retention_item(dynamic raw);

  @protected
  List<Segment> dco_decode_list_segment(dynamic raw);

  @protected
  List<SessionAge> dco_decode_list_session_age(dynamic raw);

  @protected
  List<SessionEvent> dco_decode_list_session_event(dynamic raw);

  @protected
  List<TimeRange> dco_decode_list_time_range(dynamic raw);

  @protected
  List<TindakLanjut> dco_decode_list_tindak_lanjut(dynamic raw);

  @protected
  ModelInfo dco_decode_model_info(dynamic raw);

  @protected
  NoticeLevel dco_decode_notice_level(dynamic raw);

  @protected
  NotulenDefaults dco_decode_notulen_defaults(dynamic raw);

  @protected
  NotulenDraft dco_decode_notulen_draft(dynamic raw);

  @protected
  NotulenForm dco_decode_notulen_form(dynamic raw);

  @protected
  NotulenVariant dco_decode_notulen_variant(dynamic raw);

  @protected
  Map<String, String>? dco_decode_opt_Map_String_String_None(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BatchProgressSnapshot? dco_decode_opt_box_autoadd_batch_progress_snapshot(
    dynamic raw,
  );

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  (BigInt, BigInt)? dco_decode_opt_box_autoadd_record_u_64_u_64(dynamic raw);

  @protected
  TranscribeFileResult? dco_decode_opt_box_autoadd_transcribe_file_result(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PdpSettings dco_decode_pdp_settings(dynamic raw);

  @protected
  PiiKind dco_decode_pii_kind(dynamic raw);

  @protected
  PiiMatch dco_decode_pii_match(dynamic raw);

  @protected
  ProgressiveFileResult dco_decode_progressive_file_result(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw);

  @protected
  RecoverableSession dco_decode_recoverable_session(dynamic raw);

  @protected
  RecoveredSession dco_decode_recovered_session(dynamic raw);

  @protected
  RedactionConfig dco_decode_redaction_config(dynamic raw);

  @protected
  RetentionItem dco_decode_retention_item(dynamic raw);

  @protected
  RetentionOutcome dco_decode_retention_outcome(dynamic raw);

  @protected
  RetentionPlan dco_decode_retention_plan(dynamic raw);

  @protected
  RetentionPolicy dco_decode_retention_policy(dynamic raw);

  @protected
  Segment dco_decode_segment(dynamic raw);

  @protected
  SessionAge dco_decode_session_age(dynamic raw);

  @protected
  SessionConfig dco_decode_session_config(dynamic raw);

  @protected
  SessionEvent dco_decode_session_event(dynamic raw);

  @protected
  SessionMode dco_decode_session_mode(dynamic raw);

  @protected
  SessionRecoverySnapshot dco_decode_session_recovery_snapshot(dynamic raw);

  @protected
  SessionStatus dco_decode_session_status(dynamic raw);

  @protected
  SummaryConfig dco_decode_summary_config(dynamic raw);

  @protected
  SummaryProvider dco_decode_summary_provider(dynamic raw);

  @protected
  SummarySettings dco_decode_summary_settings(dynamic raw);

  @protected
  SummaryTemplate dco_decode_summary_template(dynamic raw);

  @protected
  Theme dco_decode_theme(dynamic raw);

  @protected
  TimeRange dco_decode_time_range(dynamic raw);

  @protected
  TindakLanjut dco_decode_tindak_lanjut(dynamic raw);

  @protected
  TranscribeError dco_decode_transcribe_error(dynamic raw);

  @protected
  TranscribeFileResult dco_decode_transcribe_file_result(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  AudioDeviceInfo sse_decode_audio_device_info(SseDeserializer deserializer);

  @protected
  AuditAction sse_decode_audit_action(SseDeserializer deserializer);

  @protected
  AuditEntry sse_decode_audit_entry(SseDeserializer deserializer);

  @protected
  BatchFileOutcome sse_decode_batch_file_outcome(SseDeserializer deserializer);

  @protected
  BatchFileStatus sse_decode_batch_file_status(SseDeserializer deserializer);

  @protected
  BatchProgressSnapshot sse_decode_batch_progress_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  Bookmark sse_decode_bookmark(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  BatchProgressSnapshot sse_decode_box_autoadd_batch_progress_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  GlossaryConfig sse_decode_box_autoadd_glossary_config(
    SseDeserializer deserializer,
  );

  @protected
  NotulenForm sse_decode_box_autoadd_notulen_form(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt) sse_decode_box_autoadd_record_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  RedactionConfig sse_decode_box_autoadd_redaction_config(
    SseDeserializer deserializer,
  );

  @protected
  RetentionPlan sse_decode_box_autoadd_retention_plan(
    SseDeserializer deserializer,
  );

  @protected
  RetentionPolicy sse_decode_box_autoadd_retention_policy(
    SseDeserializer deserializer,
  );

  @protected
  Segment sse_decode_box_autoadd_segment(SseDeserializer deserializer);

  @protected
  SessionConfig sse_decode_box_autoadd_session_config(
    SseDeserializer deserializer,
  );

  @protected
  SessionRecoverySnapshot sse_decode_box_autoadd_session_recovery_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  SummaryConfig sse_decode_box_autoadd_summary_config(
    SseDeserializer deserializer,
  );

  @protected
  TranscribeFileResult sse_decode_box_autoadd_transcribe_file_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CaptureHealth sse_decode_capture_health(SseDeserializer deserializer);

  @protected
  ChannelCapture sse_decode_channel_capture(SseDeserializer deserializer);

  @protected
  ChannelCounters sse_decode_channel_counters(SseDeserializer deserializer);

  @protected
  Check sse_decode_check(SseDeserializer deserializer);

  @protected
  CheckStatus sse_decode_check_status(SseDeserializer deserializer);

  @protected
  CompletionOutcome sse_decode_completion_outcome(SseDeserializer deserializer);

  @protected
  CompletionProgress sse_decode_completion_progress(
    SseDeserializer deserializer,
  );

  @protected
  CoverageReport sse_decode_coverage_report(SseDeserializer deserializer);

  @protected
  CustomSummaryTemplate sse_decode_custom_summary_template(
    SseDeserializer deserializer,
  );

  @protected
  DiskSpaceLevel sse_decode_disk_space_level(SseDeserializer deserializer);

  @protected
  DiskSpaceStatus sse_decode_disk_space_status(SseDeserializer deserializer);

  @protected
  ExportFormat sse_decode_export_format(SseDeserializer deserializer);

  @protected
  ExportedFile sse_decode_exported_file(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GlossaryConfig sse_decode_glossary_config(SseDeserializer deserializer);

  @protected
  GlossaryPromptInfo sse_decode_glossary_prompt_info(
    SseDeserializer deserializer,
  );

  @protected
  GlossarySettings sse_decode_glossary_settings(SseDeserializer deserializer);

  @protected
  GpuCapability sse_decode_gpu_capability(SseDeserializer deserializer);

  @protected
  HptMode sse_decode_hpt_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AudioDeviceInfo> sse_decode_list_audio_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<AuditEntry> sse_decode_list_audit_entry(SseDeserializer deserializer);

  @protected
  List<BatchFileOutcome> sse_decode_list_batch_file_outcome(
    SseDeserializer deserializer,
  );

  @protected
  List<Bookmark> sse_decode_list_bookmark(SseDeserializer deserializer);

  @protected
  List<ChannelCapture> sse_decode_list_channel_capture(
    SseDeserializer deserializer,
  );

  @protected
  List<Check> sse_decode_list_check(SseDeserializer deserializer);

  @protected
  List<CompletionProgress> sse_decode_list_completion_progress(
    SseDeserializer deserializer,
  );

  @protected
  List<CustomSummaryTemplate> sse_decode_list_custom_summary_template(
    SseDeserializer deserializer,
  );

  @protected
  List<ExportFormat> sse_decode_list_export_format(
    SseDeserializer deserializer,
  );

  @protected
  List<ExportedFile> sse_decode_list_exported_file(
    SseDeserializer deserializer,
  );

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer);

  @protected
  List<PiiMatch> sse_decode_list_pii_match(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<RecoverableSession> sse_decode_list_recoverable_session(
    SseDeserializer deserializer,
  );

  @protected
  List<RetentionItem> sse_decode_list_retention_item(
    SseDeserializer deserializer,
  );

  @protected
  List<Segment> sse_decode_list_segment(SseDeserializer deserializer);

  @protected
  List<SessionAge> sse_decode_list_session_age(SseDeserializer deserializer);

  @protected
  List<SessionEvent> sse_decode_list_session_event(
    SseDeserializer deserializer,
  );

  @protected
  List<TimeRange> sse_decode_list_time_range(SseDeserializer deserializer);

  @protected
  List<TindakLanjut> sse_decode_list_tindak_lanjut(
    SseDeserializer deserializer,
  );

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer);

  @protected
  NoticeLevel sse_decode_notice_level(SseDeserializer deserializer);

  @protected
  NotulenDefaults sse_decode_notulen_defaults(SseDeserializer deserializer);

  @protected
  NotulenDraft sse_decode_notulen_draft(SseDeserializer deserializer);

  @protected
  NotulenForm sse_decode_notulen_form(SseDeserializer deserializer);

  @protected
  NotulenVariant sse_decode_notulen_variant(SseDeserializer deserializer);

  @protected
  Map<String, String>? sse_decode_opt_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BatchProgressSnapshot? sse_decode_opt_box_autoadd_batch_progress_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  (BigInt, BigInt)? sse_decode_opt_box_autoadd_record_u_64_u_64(
    SseDeserializer deserializer,
  );

  @protected
  TranscribeFileResult? sse_decode_opt_box_autoadd_transcribe_file_result(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PdpSettings sse_decode_pdp_settings(SseDeserializer deserializer);

  @protected
  PiiKind sse_decode_pii_kind(SseDeserializer deserializer);

  @protected
  PiiMatch sse_decode_pii_match(SseDeserializer deserializer);

  @protected
  ProgressiveFileResult sse_decode_progressive_file_result(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer);

  @protected
  RecoverableSession sse_decode_recoverable_session(
    SseDeserializer deserializer,
  );

  @protected
  RecoveredSession sse_decode_recovered_session(SseDeserializer deserializer);

  @protected
  RedactionConfig sse_decode_redaction_config(SseDeserializer deserializer);

  @protected
  RetentionItem sse_decode_retention_item(SseDeserializer deserializer);

  @protected
  RetentionOutcome sse_decode_retention_outcome(SseDeserializer deserializer);

  @protected
  RetentionPlan sse_decode_retention_plan(SseDeserializer deserializer);

  @protected
  RetentionPolicy sse_decode_retention_policy(SseDeserializer deserializer);

  @protected
  Segment sse_decode_segment(SseDeserializer deserializer);

  @protected
  SessionAge sse_decode_session_age(SseDeserializer deserializer);

  @protected
  SessionConfig sse_decode_session_config(SseDeserializer deserializer);

  @protected
  SessionEvent sse_decode_session_event(SseDeserializer deserializer);

  @protected
  SessionMode sse_decode_session_mode(SseDeserializer deserializer);

  @protected
  SessionRecoverySnapshot sse_decode_session_recovery_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  SessionStatus sse_decode_session_status(SseDeserializer deserializer);

  @protected
  SummaryConfig sse_decode_summary_config(SseDeserializer deserializer);

  @protected
  SummaryProvider sse_decode_summary_provider(SseDeserializer deserializer);

  @protected
  SummarySettings sse_decode_summary_settings(SseDeserializer deserializer);

  @protected
  SummaryTemplate sse_decode_summary_template(SseDeserializer deserializer);

  @protected
  Theme sse_decode_theme(SseDeserializer deserializer);

  @protected
  TimeRange sse_decode_time_range(SseDeserializer deserializer);

  @protected
  TindakLanjut sse_decode_tindak_lanjut(SseDeserializer deserializer);

  @protected
  TranscribeError sse_decode_transcribe_error(SseDeserializer deserializer);

  @protected
  TranscribeFileResult sse_decode_transcribe_file_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_audio_device_info(
    AudioDeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audit_action(AuditAction self, SseSerializer serializer);

  @protected
  void sse_encode_audit_entry(AuditEntry self, SseSerializer serializer);

  @protected
  void sse_encode_batch_file_outcome(
    BatchFileOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_file_status(
    BatchFileStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_progress_snapshot(
    BatchProgressSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bookmark(Bookmark self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_batch_progress_snapshot(
    BatchProgressSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_glossary_config(
    GlossaryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_notulen_form(
    NotulenForm self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_redaction_config(
    RedactionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_retention_plan(
    RetentionPlan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_retention_policy(
    RetentionPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_segment(Segment self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_session_config(
    SessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_recovery_snapshot(
    SessionRecoverySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_summary_config(
    SummaryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transcribe_file_result(
    TranscribeFileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_capture_health(CaptureHealth self, SseSerializer serializer);

  @protected
  void sse_encode_channel_capture(
    ChannelCapture self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channel_counters(
    ChannelCounters self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_check(Check self, SseSerializer serializer);

  @protected
  void sse_encode_check_status(CheckStatus self, SseSerializer serializer);

  @protected
  void sse_encode_completion_outcome(
    CompletionOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_completion_progress(
    CompletionProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_coverage_report(
    CoverageReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_summary_template(
    CustomSummaryTemplate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_disk_space_level(
    DiskSpaceLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_disk_space_status(
    DiskSpaceStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_format(ExportFormat self, SseSerializer serializer);

  @protected
  void sse_encode_exported_file(ExportedFile self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_glossary_config(
    GlossaryConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_glossary_prompt_info(
    GlossaryPromptInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_glossary_settings(
    GlossarySettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gpu_capability(GpuCapability self, SseSerializer serializer);

  @protected
  void sse_encode_hpt_mode(HptMode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_device_info(
    List<AudioDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_audit_entry(
    List<AuditEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_batch_file_outcome(
    List<BatchFileOutcome> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bookmark(List<Bookmark> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel_capture(
    List<ChannelCapture> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_check(List<Check> self, SseSerializer serializer);

  @protected
  void sse_encode_list_completion_progress(
    List<CompletionProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_custom_summary_template(
    List<CustomSummaryTemplate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_export_format(
    List<ExportFormat> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_exported_file(
    List<ExportedFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_model_info(
    List<ModelInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pii_match(List<PiiMatch> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recoverable_session(
    List<RecoverableSession> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_retention_item(
    List<RetentionItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_segment(List<Segment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_session_age(
    List<SessionAge> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_event(
    List<SessionEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_time_range(
    List<TimeRange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tindak_lanjut(
    List<TindakLanjut> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_notice_level(NoticeLevel self, SseSerializer serializer);

  @protected
  void sse_encode_notulen_defaults(
    NotulenDefaults self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notulen_draft(NotulenDraft self, SseSerializer serializer);

  @protected
  void sse_encode_notulen_form(NotulenForm self, SseSerializer serializer);

  @protected
  void sse_encode_notulen_variant(
    NotulenVariant self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_Map_String_String_None(
    Map<String, String>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_batch_progress_snapshot(
    BatchProgressSnapshot? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_record_u_64_u_64(
    (BigInt, BigInt)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_transcribe_file_result(
    TranscribeFileResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pdp_settings(PdpSettings self, SseSerializer serializer);

  @protected
  void sse_encode_pii_kind(PiiKind self, SseSerializer serializer);

  @protected
  void sse_encode_pii_match(PiiMatch self, SseSerializer serializer);

  @protected
  void sse_encode_progressive_file_result(
    ProgressiveFileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recoverable_session(
    RecoverableSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovered_session(
    RecoveredSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_redaction_config(
    RedactionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_retention_item(RetentionItem self, SseSerializer serializer);

  @protected
  void sse_encode_retention_outcome(
    RetentionOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_retention_plan(RetentionPlan self, SseSerializer serializer);

  @protected
  void sse_encode_retention_policy(
    RetentionPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_segment(Segment self, SseSerializer serializer);

  @protected
  void sse_encode_session_age(SessionAge self, SseSerializer serializer);

  @protected
  void sse_encode_session_config(SessionConfig self, SseSerializer serializer);

  @protected
  void sse_encode_session_event(SessionEvent self, SseSerializer serializer);

  @protected
  void sse_encode_session_mode(SessionMode self, SseSerializer serializer);

  @protected
  void sse_encode_session_recovery_snapshot(
    SessionRecoverySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_status(SessionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_summary_config(SummaryConfig self, SseSerializer serializer);

  @protected
  void sse_encode_summary_provider(
    SummaryProvider self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_summary_settings(
    SummarySettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_summary_template(
    SummaryTemplate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_theme(Theme self, SseSerializer serializer);

  @protected
  void sse_encode_time_range(TimeRange self, SseSerializer serializer);

  @protected
  void sse_encode_tindak_lanjut(TindakLanjut self, SseSerializer serializer);

  @protected
  void sse_encode_transcribe_error(
    TranscribeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcribe_file_result(
    TranscribeFileResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
