// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Glossary terms plus the two switches, as carried on a session.
///
/// Split into global and per-session lists rather than one merged list
/// because the split is exactly what the prioritisation rule needs: when
/// the prompt budget cannot hold everything, the terms the notulis typed
/// *for this meeting* are the ones that must survive.
class GlossaryConfig {
  /// Terms added for this meeting only. Highest priority.
  final List<String> sessionTerms;

  /// The persistent list from Settings.
  final List<String> globalTerms;

  /// Run [`apply_corrections`] over each segment after inference.
  final bool postCorrection;

  const GlossaryConfig({
    required this.sessionTerms,
    required this.globalTerms,
    required this.postCorrection,
  });

  @override
  int get hashCode =>
      sessionTerms.hashCode ^ globalTerms.hashCode ^ postCorrection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlossaryConfig &&
          runtimeType == other.runtimeType &&
          sessionTerms == other.sessionTerms &&
          globalTerms == other.globalTerms &&
          postCorrection == other.postCorrection;
}
