// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What the machine can run.
class HardwareProfile {
  final double ramGb;

  /// Dedicated GPU memory, or 0.0 when there is none or it is unknown.
  final double vramGb;
  final int cpuThreads;

  const HardwareProfile({
    required this.ramGb,
    required this.vramGb,
    required this.cpuThreads,
  });

  @override
  int get hashCode => ramGb.hashCode ^ vramGb.hashCode ^ cpuThreads.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HardwareProfile &&
          runtimeType == other.runtimeType &&
          ramGb == other.ramGb &&
          vramGb == other.vramGb &&
          cpuThreads == other.cpuThreads;
}

/// How to install Ollama on one operating system.
class InstallGuide {
  /// "macOS", "Windows", "Linux".
  final String sistem;

  /// Numbered steps, in Indonesian.
  final List<String> langkah;

  /// The official download page.
  final String tautan;

  /// A command the user can copy, or empty when the install is a
  /// downloaded installer.
  final String perintah;

  const InstallGuide({
    required this.sistem,
    required this.langkah,
    required this.tautan,
    required this.perintah,
  });

  @override
  int get hashCode =>
      sistem.hashCode ^ langkah.hashCode ^ tautan.hashCode ^ perintah.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstallGuide &&
          runtimeType == other.runtimeType &&
          sistem == other.sistem &&
          langkah == other.langkah &&
          tautan == other.tautan &&
          perintah == other.perintah;
}

/// Which of the three answers a machine gets.
enum LlmTier {
  /// Runs on a 4-core laptop with no GPU. Slow but finishes.
  ringan,

  /// The default: the best quality that fits a 16 GB machine.
  seimbang,

  /// For a workstation or a GPU with 8 GB or more.
  berat,
}

/// One entry of the model catalogue the setup step offers.
class ModelOption {
  /// Ollama tag, exactly as `ollama pull` takes it.
  final String tag;
  final String label;
  final LlmTier tier;

  /// Download size, GiB.
  final double unduhGb;

  /// Resident footprint while generating, GiB — measured, not the
  /// download size.
  final double residenGb;

  /// Context window the tag advertises, in tokens.
  final int konteks;
  final String lisensi;

  /// One or two sentences, in Indonesian, on when to pick this.
  final String catatan;

  const ModelOption({
    required this.tag,
    required this.label,
    required this.tier,
    required this.unduhGb,
    required this.residenGb,
    required this.konteks,
    required this.lisensi,
    required this.catatan,
  });

  @override
  int get hashCode =>
      tag.hashCode ^
      label.hashCode ^
      tier.hashCode ^
      unduhGb.hashCode ^
      residenGb.hashCode ^
      konteks.hashCode ^
      lisensi.hashCode ^
      catatan.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelOption &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          label == other.label &&
          tier == other.tier &&
          unduhGb == other.unduhGb &&
          residenGb == other.residenGb &&
          konteks == other.konteks &&
          lisensi == other.lisensi &&
          catatan == other.catatan;
}

/// One line of Ollama's `/api/pull` stream, parsed.
class PullProgress {
  /// Ollama's own status text, e.g. "pulling manifest".
  final String status;

  /// Indonesian rendering of `status`, for the UI.
  final String label;
  final BigInt selesaiBytes;
  final BigInt totalBytes;

  /// `true` once the pull has finished successfully.
  final bool done;

  const PullProgress({
    required this.status,
    required this.label,
    required this.selesaiBytes,
    required this.totalBytes,
    required this.done,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      label.hashCode ^
      selesaiBytes.hashCode ^
      totalBytes.hashCode ^
      done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PullProgress &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          label == other.label &&
          selesaiBytes == other.selesaiBytes &&
          totalBytes == other.totalBytes &&
          done == other.done;
}

/// What the setup step recommends for this machine.
class Recommendation {
  final ModelOption model;

  /// Why this one, in Indonesian, naming the machine's numbers.
  final String alasan;

  /// `true` when nothing in the catalogue fits and the recommendation
  /// is the lightest option as a best effort.
  final bool terlaluKecil;

  const Recommendation({
    required this.model,
    required this.alasan,
    required this.terlaluKecil,
  });

  @override
  int get hashCode => model.hashCode ^ alasan.hashCode ^ terlaluKecil.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recommendation &&
          runtimeType == other.runtimeType &&
          model == other.model &&
          alasan == other.alasan &&
          terlaluKecil == other.terlaluKecil;
}
