// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// How far through a map-reduce run the caller is.
class MapReduceProgress {
  /// 0-based count of windows already summarised.
  final int done;
  final int total;

  /// Indonesian line for the UI.
  final String label;

  const MapReduceProgress({
    required this.done,
    required this.total,
    required this.label,
  });

  @override
  int get hashCode => done.hashCode ^ total.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapReduceProgress &&
          runtimeType == other.runtimeType &&
          done == other.done &&
          total == other.total &&
          label == other.label;
}
