// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// The three kinds of thing the model manager downloads.
///
/// Before Sprint 4b the catalog held only Whisper models, so "model" and
/// "downloadable asset" were the same word. The Silero VAD gate and the
/// optional neural diarization both need files on disk with the same
/// resume + checksum + Privacy Report treatment, and nothing else about
/// them resembles a transcription model: they are not selectable, they
/// have no RAM floor worth showing, and listing them in the Settings
/// dropdown would offer the user a 28 MB speaker-embedding network as a
/// choice of transcriber.
enum AssetKind {
  /// A Whisper GGML model.
  transcription,

  /// whisper.cpp's Silero voice-activity model.
  vad,

  /// A sherpa-onnx speaker-diarization model.
  diarization,
}

class ModelInfo {
  final String id;
  final String name;
  final String url;
  final String sha256;
  final BigInt sizeBytes;
  final int minRamGb;
  final bool isBundled;

  /// What this asset is *for*. The model picker only ever offers
  /// [`AssetKind::Transcription`]; the VAD and diarization assets are
  /// downloaded because a feature was switched on, not chosen from a
  /// list.
  final AssetKind kind;

  const ModelInfo({
    required this.id,
    required this.name,
    required this.url,
    required this.sha256,
    required this.sizeBytes,
    required this.minRamGb,
    required this.isBundled,
    required this.kind,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      url.hashCode ^
      sha256.hashCode ^
      sizeBytes.hashCode ^
      minRamGb.hashCode ^
      isBundled.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          url == other.url &&
          sha256 == other.sha256 &&
          sizeBytes == other.sizeBytes &&
          minRamGb == other.minRamGb &&
          isBundled == other.isBundled &&
          kind == other.kind;
}
