// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_resume_request`, `download_single_url`, `set_download_progress`, `write_download_stream`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DownloadProgress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `is_model_downloaded`, `list_available_models`, `read_download_progress`, `reset_download_progress`, `resolve_model_info`, `resolve_model_path`, `verify_checksum`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `download_with_resume`

class ModelInfo {
  final String id;
  final String name;
  final String url;
  final String sha256;
  final BigInt sizeBytes;
  final int minRamGb;
  final bool isBundled;

  const ModelInfo({
    required this.id,
    required this.name,
    required this.url,
    required this.sha256,
    required this.sizeBytes,
    required this.minRamGb,
    required this.isBundled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      url.hashCode ^
      sha256.hashCode ^
      sizeBytes.hashCode ^
      minRamGb.hashCode ^
      isBundled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          url == other.url &&
          sha256 == other.sha256 &&
          sizeBytes == other.sizeBytes &&
          minRamGb == other.minRamGb &&
          isBundled == other.isBundled;
}
