// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Which naskah-dinas layout the notulen is being written as.
///
/// Serialised by name into `settings.json` and the session's saved form,
/// so the variant names are a storage format: renaming one needs a
/// migration.
enum NotulenTemplate {
  /// Full notula per Pedoman Tata Naskah Dinas: identitas rapat,
  /// peserta, acara, jalannya rapat, kesimpulan, tindak lanjut, tanda
  /// tangan notulis + pimpinan.
  dinas,

  /// Risalah rapat, verbatim-ringkas: the order of speakers is the
  /// point, so `jalannya_rapat` is required and carries one entry per
  /// intervention.
  risalah,

  /// Berita acara: para pihak, what was carried out, and the closing
  /// formula. Used for serah terima, pemeriksaan and kesepakatan.
  beritaAcara,

  /// One page, no kop surat, no signature block.
  ringkas,
}
