// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pdp/redaction.dart';
import 'pdp/retention.dart';

/// Everything "Mode Kepatuhan PDP" switches on, as stored in settings.
class PdpSettings {
  /// Master switch. With it off the app behaves exactly as before.
  final bool enabled;
  final RedactionConfig redaction;
  final RetentionPolicy retention;

  /// Show the consent reminder before a recording starts.
  final bool consentReminder;

  /// The reminder text, so an organisation can use its own wording.
  /// Empty falls back to [`DEFAULT_CONSENT_NOTICE`].
  final String consentText;

  const PdpSettings({
    required this.enabled,
    required this.redaction,
    required this.retention,
    required this.consentReminder,
    required this.consentText,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      redaction.hashCode ^
      retention.hashCode ^
      consentReminder.hashCode ^
      consentText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PdpSettings &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          redaction == other.redaction &&
          retention == other.retention &&
          consentReminder == other.consentReminder &&
          consentText == other.consentText;
}
