// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A pointer from a summary line back into the transcript.
class Citation {
  /// 1-based segment number, as shown to the model.
  final int segmentId;

  /// Where that segment starts, so the player can seek without
  /// re-resolving the id.
  final double timestamp;

  const Citation({required this.segmentId, required this.timestamp});

  @override
  int get hashCode => segmentId.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Citation &&
          runtimeType == other.runtimeType &&
          segmentId == other.segmentId &&
          timestamp == other.timestamp;
}

/// One line of the summary, with whatever it cited.
class SummaryLine {
  /// The line with its citation markers removed, ready to render.
  final String text;
  final List<Citation> citations;

  /// True for a `#`/`##` heading, so the UI can style it as one rather
  /// than hanging citation chips off it.
  final bool isHeading;

  const SummaryLine({
    required this.text,
    required this.citations,
    required this.isHeading,
  });

  @override
  int get hashCode => text.hashCode ^ citations.hashCode ^ isHeading.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SummaryLine &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          citations == other.citations &&
          isHeading == other.isHeading;
}

/// A parsed summary plus what was thrown away.
class SummaryProvenance {
  final List<SummaryLine> lines;

  /// Citations dropped for pointing outside the transcript. Surfaced
  /// rather than swallowed: a summary with many of these came from a
  /// model that is guessing, and the user should be told.
  final int dropped;

  const SummaryProvenance({required this.lines, required this.dropped});

  @override
  int get hashCode => lines.hashCode ^ dropped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SummaryProvenance &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          dropped == other.dropped;
}
