// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio.dart';
import 'error.dart';
import 'export.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'session.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `accept_or_drop_echo`, `audio_registry`, `collect_worker_events`, `load_snapshot_file`, `persist_session_snapshot`, `recovery_dir`, `recovery_path`, `registry`, `remove_snapshot_file`, `should_split`, `start_capture`, `start_session_with_id`, `trim_recent_emitted`, `unix_ms_now`, `with_session_mut`, `write_snapshot_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CaptureChannel`, `SessionState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Takes (removes) the raw mic/speaker audio retained for `session_id`, if
/// any. Returns `(None, None)` if the session had no live capture (e.g. it
/// was never started, or was a batch-file transcription) or if this was
/// already called for this session.
Future<(Float32List?, Float32List?)> takeRawAudio({
  required String sessionId,
}) => RustLib.instance.api.crateSessionTakeRawAudio(sessionId: sessionId);

Future<String> startSession({required SessionConfig config}) =>
    RustLib.instance.api.crateSessionStartSession(config: config);

Future<String> recoverSession({required SessionRecoverySnapshot snapshot}) =>
    RustLib.instance.api.crateSessionRecoverSession(snapshot: snapshot);

Future<void> stopSession({required String sessionId}) =>
    RustLib.instance.api.crateSessionStopSession(sessionId: sessionId);

Future<void> toggleMic({required String sessionId, required bool enabled}) =>
    RustLib.instance.api.crateSessionToggleMic(
      sessionId: sessionId,
      enabled: enabled,
    );

Future<void> toggleSpeaker({
  required String sessionId,
  required bool enabled,
}) => RustLib.instance.api.crateSessionToggleSpeaker(
  sessionId: sessionId,
  enabled: enabled,
);

Future<void> setSessionMode({
  required String sessionId,
  required SessionMode mode,
}) => RustLib.instance.api.crateSessionSetSessionMode(
  sessionId: sessionId,
  mode: mode,
);

Future<void> recordSegment({required String sessionId}) =>
    RustLib.instance.api.crateSessionRecordSegment(sessionId: sessionId);

/// Call periodically (e.g. every minute) from the live capture loop. If it
/// returns `Some`, the caller should flush the current chunk to disk and
/// start a new file segment, then call [`mark_split`].
Future<AutoSplitReason?> checkAutoSplit({required String sessionId}) =>
    RustLib.instance.api.crateSessionCheckAutoSplit(sessionId: sessionId);

Future<void> markSplit({required String sessionId}) =>
    RustLib.instance.api.crateSessionMarkSplit(sessionId: sessionId);

Future<SessionStatus> getStatus({required String sessionId}) =>
    RustLib.instance.api.crateSessionGetStatus(sessionId: sessionId);

Future<List<SessionEvent>> pollEvents({required String sessionId}) =>
    RustLib.instance.api.crateSessionPollEvents(sessionId: sessionId);

Future<List<SessionRecoverySnapshot>> listRecoverableSessions() =>
    RustLib.instance.api.crateSessionListRecoverableSessions();

enum AutoSplitReason { timeBoundary, memoryPressure }

@freezed
sealed class SessionEvent with _$SessionEvent {
  const SessionEvent._();

  const factory SessionEvent.transcript(Segment field0) =
      SessionEvent_Transcript;
  const factory SessionEvent.vu({
    required String source,
    required double level,
  }) = SessionEvent_Vu;
}

class SessionRecoverySnapshot {
  final String sessionId;
  final SessionConfig config;
  final BigInt startedAtUnixMs;
  final BigInt lastSplitAtUnixMs;
  final int segmentsCount;

  const SessionRecoverySnapshot({
    required this.sessionId,
    required this.config,
    required this.startedAtUnixMs,
    required this.lastSplitAtUnixMs,
    required this.segmentsCount,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      config.hashCode ^
      startedAtUnixMs.hashCode ^
      lastSplitAtUnixMs.hashCode ^
      segmentsCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionRecoverySnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          config == other.config &&
          startedAtUnixMs == other.startedAtUnixMs &&
          lastSplitAtUnixMs == other.lastSplitAtUnixMs &&
          segmentsCount == other.segmentsCount;
}

class SessionStatus {
  final String sessionId;
  final double elapsedSeconds;
  final bool micEnabled;
  final bool speakerEnabled;
  final int segmentsCount;
  final bool modelLoaded;

  const SessionStatus({
    required this.sessionId,
    required this.elapsedSeconds,
    required this.micEnabled,
    required this.speakerEnabled,
    required this.segmentsCount,
    required this.modelLoaded,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      elapsedSeconds.hashCode ^
      micEnabled.hashCode ^
      speakerEnabled.hashCode ^
      segmentsCount.hashCode ^
      modelLoaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionStatus &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          elapsedSeconds == other.elapsedSeconds &&
          micEnabled == other.micEnabled &&
          speakerEnabled == other.speakerEnabled &&
          segmentsCount == other.segmentsCount &&
          modelLoaded == other.modelLoaded;
}
