// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio.dart';
import 'export.dart';
import 'frb_generated.dart';
import 'glossary.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'session.freezed.dart';

/// Snapshot of a running session's capture health.
class CaptureHealth {
  final String sessionId;
  final double elapsedSecs;
  final int segmentCount;
  final List<ChannelCapture> channels;

  /// Ready-to-show Indonesian warnings — an expected source that has
  /// delivered nothing, or one that has gone quiet for a long time.
  final List<String> warnings;

  const CaptureHealth({
    required this.sessionId,
    required this.elapsedSecs,
    required this.segmentCount,
    required this.channels,
    required this.warnings,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      elapsedSecs.hashCode ^
      segmentCount.hashCode ^
      channels.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureHealth &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          elapsedSecs == other.elapsedSecs &&
          segmentCount == other.segmentCount &&
          channels == other.channels &&
          warnings == other.warnings;
}

/// Live capture health for one source. Drives both the "rekaman
/// terkonfirmasi" indicator during recording and the integrity summary at
/// Stop, so the two can never disagree.
class ChannelCapture {
  /// `"mic"` or `"spk"`.
  final String source;

  /// Whether the user asked for this source at all.
  final bool expected;

  /// Audio above the noise floor has been observed. An open stream that
  /// has delivered nothing is *not* confirmed — that distinction is the
  /// whole point.
  final bool confirmed;
  final double secondsCaptured;
  final double secondsVoiced;
  final double percentSilent;

  /// How long this source has been below the noise floor.
  final double silentForSecs;

  /// False when this source fell back to (or was demoted to) RAM.
  final bool writingToDisk;

  const ChannelCapture({
    required this.source,
    required this.expected,
    required this.confirmed,
    required this.secondsCaptured,
    required this.secondsVoiced,
    required this.percentSilent,
    required this.silentForSecs,
    required this.writingToDisk,
  });

  @override
  int get hashCode =>
      source.hashCode ^
      expected.hashCode ^
      confirmed.hashCode ^
      secondsCaptured.hashCode ^
      secondsVoiced.hashCode ^
      percentSilent.hashCode ^
      silentForSecs.hashCode ^
      writingToDisk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelCapture &&
          runtimeType == other.runtimeType &&
          source == other.source &&
          expected == other.expected &&
          confirmed == other.confirmed &&
          secondsCaptured == other.secondsCaptured &&
          secondsVoiced == other.secondsVoiced &&
          percentSilent == other.percentSilent &&
          silentForSecs == other.silentForSecs &&
          writingToDisk == other.writingToDisk;
}

/// How much audio one source has delivered, and how much of it was above
/// the noise floor. Persisted so it survives a crash.
class ChannelCounters {
  final BigInt totalSamples;
  final BigInt voicedSamples;

  const ChannelCounters({
    required this.totalSamples,
    required this.voicedSamples,
  });

  @override
  int get hashCode => totalSamples.hashCode ^ voicedSamples.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelCounters &&
          runtimeType == other.runtimeType &&
          totalSamples == other.totalSamples &&
          voicedSamples == other.voicedSamples;
}

enum NoticeLevel {
  /// The session is running, but with less than the user asked for.
  warning,

  /// Something the user asked for has stopped working.
  error,
}

/// One entry in the recovery dialog: the snapshot plus what is actually
/// on disk for it. Computed at listing time rather than persisted, because
/// the honest answer to "what can be recovered" is whatever survived the
/// crash, not whatever the app last claimed.
class RecoverableSession {
  final SessionRecoverySnapshot snapshot;

  /// Falls back to the session id when the session was never titled.
  final String title;
  final BigInt startedAtUnixMs;
  final BigInt updatedAtUnixMs;
  final double durationSecs;

  /// Segments actually present in the journal — not the count the
  /// snapshot claimed, which is what the old banner reported.
  final int segmentCount;
  final double micAudioSecs;
  final double speakerAudioSecs;

  const RecoverableSession({
    required this.snapshot,
    required this.title,
    required this.startedAtUnixMs,
    required this.updatedAtUnixMs,
    required this.durationSecs,
    required this.segmentCount,
    required this.micAudioSecs,
    required this.speakerAudioSecs,
  });

  @override
  int get hashCode =>
      snapshot.hashCode ^
      title.hashCode ^
      startedAtUnixMs.hashCode ^
      updatedAtUnixMs.hashCode ^
      durationSecs.hashCode ^
      segmentCount.hashCode ^
      micAudioSecs.hashCode ^
      speakerAudioSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoverableSession &&
          runtimeType == other.runtimeType &&
          snapshot == other.snapshot &&
          title == other.title &&
          startedAtUnixMs == other.startedAtUnixMs &&
          updatedAtUnixMs == other.updatedAtUnixMs &&
          durationSecs == other.durationSecs &&
          segmentCount == other.segmentCount &&
          micAudioSecs == other.micAudioSecs &&
          speakerAudioSecs == other.speakerAudioSecs;
}

/// What [`recover_session`] gives back: the restored session plus the
/// transcript that used to be silently dropped.
class RecoveredSession {
  final String sessionId;
  final List<Segment> segments;

  /// Where the restored timeline ends; new segments continue from here.
  final double resumeOffsetSecs;
  final double micAudioSecs;
  final double speakerAudioSecs;

  const RecoveredSession({
    required this.sessionId,
    required this.segments,
    required this.resumeOffsetSecs,
    required this.micAudioSecs,
    required this.speakerAudioSecs,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      segments.hashCode ^
      resumeOffsetSecs.hashCode ^
      micAudioSecs.hashCode ^
      speakerAudioSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoveredSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          segments == other.segments &&
          resumeOffsetSecs == other.resumeOffsetSecs &&
          micAudioSecs == other.micAudioSecs &&
          speakerAudioSecs == other.speakerAudioSecs;
}

@freezed
sealed class SessionEvent with _$SessionEvent {
  const SessionEvent._();

  const factory SessionEvent.transcript(Segment field0) =
      SessionEvent_Transcript;
  const factory SessionEvent.vu({
    required String source,
    required double level,
  }) = SessionEvent_Vu;

  /// Something the user has to be told mid-session: a capture source that
  /// couldn't be opened, or one that died while recording. Previously these
  /// were only `tracing::warn!`ed, so a session that recorded nothing at all
  /// looked identical to one that was simply quiet.
  const factory SessionEvent.notice({
    required NoticeLevel level,
    required String source,
    required String message,
  }) = SessionEvent_Notice;
}

class SessionRecoverySnapshot {
  final String sessionId;
  final SessionConfig config;
  final BigInt startedAtUnixMs;
  final BigInt lastSplitAtUnixMs;
  final int segmentsCount;

  /// User-facing title, so the recovery dialog can name the session.
  /// Defaulted for snapshots written before it existed.
  final String title;

  /// Last time this snapshot was rewritten — i.e. roughly when the app
  /// died. `updated_at - started_at` is the session's duration.
  final BigInt updatedAtUnixMs;

  /// Seconds of timeline already consumed by earlier runs of this
  /// session, carried forward so a session recovered twice keeps
  /// accumulating rather than restarting its clock.
  final double elapsedSecs;

  /// Capture counters from earlier runs, so the integrity summary of a
  /// recovered session describes the whole meeting. Without these it
  /// reports the session's full duration next to only the seconds
  /// captured since the restart.
  final ChannelCounters micCounters;
  final ChannelCounters speakerCounters;

  const SessionRecoverySnapshot({
    required this.sessionId,
    required this.config,
    required this.startedAtUnixMs,
    required this.lastSplitAtUnixMs,
    required this.segmentsCount,
    required this.title,
    required this.updatedAtUnixMs,
    required this.elapsedSecs,
    required this.micCounters,
    required this.speakerCounters,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      config.hashCode ^
      startedAtUnixMs.hashCode ^
      lastSplitAtUnixMs.hashCode ^
      segmentsCount.hashCode ^
      title.hashCode ^
      updatedAtUnixMs.hashCode ^
      elapsedSecs.hashCode ^
      micCounters.hashCode ^
      speakerCounters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionRecoverySnapshot &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          config == other.config &&
          startedAtUnixMs == other.startedAtUnixMs &&
          lastSplitAtUnixMs == other.lastSplitAtUnixMs &&
          segmentsCount == other.segmentsCount &&
          title == other.title &&
          updatedAtUnixMs == other.updatedAtUnixMs &&
          elapsedSecs == other.elapsedSecs &&
          micCounters == other.micCounters &&
          speakerCounters == other.speakerCounters;
}

class SessionStatus {
  final String sessionId;
  final double elapsedSeconds;
  final bool micEnabled;
  final bool speakerEnabled;
  final int segmentsCount;
  final bool modelLoaded;

  const SessionStatus({
    required this.sessionId,
    required this.elapsedSeconds,
    required this.micEnabled,
    required this.speakerEnabled,
    required this.segmentsCount,
    required this.modelLoaded,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      elapsedSeconds.hashCode ^
      micEnabled.hashCode ^
      speakerEnabled.hashCode ^
      segmentsCount.hashCode ^
      modelLoaded.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionStatus &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          elapsedSeconds == other.elapsedSeconds &&
          micEnabled == other.micEnabled &&
          speakerEnabled == other.speakerEnabled &&
          segmentsCount == other.segmentsCount &&
          modelLoaded == other.modelLoaded;
}
