// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio.dart';
import 'frb_generated.dart';
import 'glossary.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'pdp.dart';
import 'pdp/redaction.dart';
import 'pdp/retention.dart';
import 'summary.dart';

class AppSettings {
  final Theme theme;
  final String defaultModel;
  final SessionMode defaultMode;
  final String libraryPath;
  final bool alwaysOnTop;
  final int autoSaveIntervalSecs;
  final bool vadEnabled;
  final bool echoDedupeEnabled;
  final String? language;

  /// Enable GPU acceleration for whisper inference (Vulkan/CUDA/Metal,
  /// whichever backend the binary was compiled with). Defaults to false
  /// so behavior is unchanged for existing installs/settings files —
  /// this is opt-in, not auto-detected, because GPU inference can be
  /// slower than CPU on low-VRAM devices once model weights don't fit.
  final bool gpuEnabled;

  /// GPU device index to use when `gpu_enabled` is true (0 = default).
  final int gpuDevice;

  /// Stop recording automatically after this many minutes without new
  /// transcript segments. `None` = never. Previously Dart-only, which meant
  /// it silently reset to "off" on every launch.
  final int? autoStopMinutes;

  /// Hybrid Progressive Transcription: quick (base) pass then refine (q5).
  final bool progressiveEnabled;

  /// Stream captured audio straight to disk instead of buffering it in
  /// RAM until Stop. On by default; see `audio::SessionConfig` for why
  /// it is a switch at all.
  final bool audioToDisk;

  /// AI summary endpoint configuration. Opt-in; see `crate::summary`.
  final SummarySettings summary;

  /// Kamus istilah — the persistent global vocabulary list. Empty by
  /// default, so the feature is inert until the user adds a term.
  final GlossarySettings glossary;

  /// User-authored summary templates, on top of the four built-ins.
  final List<CustomSummaryTemplate> summaryTemplates;

  /// Kop surat / signature defaults reused by every "Notulen Rapat" export,
  /// so a unit kerja types them once rather than per meeting.
  final NotulenDefaults notulen;

  /// Re-run the transcript with the accurate model in the background after
  /// the meeting. `None` = ask nothing and decide from the live model:
  /// default ON when the live pass used the quick model.
  final bool? autoRetranscribe;

  /// Mode Kepatuhan UU PDP (F13): redaction on export, retention limits,
  /// the audit log and the consent notice. Off by default — every part
  /// of it either hides or deletes something, so none of it may start
  /// happening because the app updated.
  final PdpSettings pdp;

  /// Run RNNoise over the audio before ASR (F17).
  ///
  /// Off by default: it is a learned suppressor, so whether it helps is
  /// a property of the room, and on already-clean speech it can cost a
  /// consonant. See `crate::denoise` for the trade-off in full.
  final bool noiseReduction;

  /// "Pemisahan pembicara akurat": run sherpa-onnx neural diarization
  /// (pyannote segmentation + CAM++ embeddings) on the post-stop, import
  /// and re-transcribe paths instead of the lightweight acoustic
  /// clustering.
  ///
  /// Off by default for three reasons: it needs ~34 MB of models the
  /// user has to agree to download, it costs roughly 0.1× realtime on
  /// top of the ASR pass, and the lightweight clustering is adequate for
  /// the two-source live case (mic = "Saya", loopback = everyone else)
  /// that most sessions are.
  final bool neuralDiarization;

  const AppSettings({
    required this.theme,
    required this.defaultModel,
    required this.defaultMode,
    required this.libraryPath,
    required this.alwaysOnTop,
    required this.autoSaveIntervalSecs,
    required this.vadEnabled,
    required this.echoDedupeEnabled,
    this.language,
    required this.gpuEnabled,
    required this.gpuDevice,
    this.autoStopMinutes,
    required this.progressiveEnabled,
    required this.audioToDisk,
    required this.summary,
    required this.glossary,
    required this.summaryTemplates,
    required this.notulen,
    this.autoRetranscribe,
    required this.pdp,
    required this.noiseReduction,
    required this.neuralDiarization,
  });

  @override
  int get hashCode =>
      theme.hashCode ^
      defaultModel.hashCode ^
      defaultMode.hashCode ^
      libraryPath.hashCode ^
      alwaysOnTop.hashCode ^
      autoSaveIntervalSecs.hashCode ^
      vadEnabled.hashCode ^
      echoDedupeEnabled.hashCode ^
      language.hashCode ^
      gpuEnabled.hashCode ^
      gpuDevice.hashCode ^
      autoStopMinutes.hashCode ^
      progressiveEnabled.hashCode ^
      audioToDisk.hashCode ^
      summary.hashCode ^
      glossary.hashCode ^
      summaryTemplates.hashCode ^
      notulen.hashCode ^
      autoRetranscribe.hashCode ^
      pdp.hashCode ^
      noiseReduction.hashCode ^
      neuralDiarization.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          defaultModel == other.defaultModel &&
          defaultMode == other.defaultMode &&
          libraryPath == other.libraryPath &&
          alwaysOnTop == other.alwaysOnTop &&
          autoSaveIntervalSecs == other.autoSaveIntervalSecs &&
          vadEnabled == other.vadEnabled &&
          echoDedupeEnabled == other.echoDedupeEnabled &&
          language == other.language &&
          gpuEnabled == other.gpuEnabled &&
          gpuDevice == other.gpuDevice &&
          autoStopMinutes == other.autoStopMinutes &&
          progressiveEnabled == other.progressiveEnabled &&
          audioToDisk == other.audioToDisk &&
          summary == other.summary &&
          glossary == other.glossary &&
          summaryTemplates == other.summaryTemplates &&
          notulen == other.notulen &&
          autoRetranscribe == other.autoRetranscribe &&
          pdp == other.pdp &&
          noiseReduction == other.noiseReduction &&
          neuralDiarization == other.neuralDiarization;
}

/// A summary template the user wrote or duplicated (F8).
///
/// `id` is a stable identifier generated when the template is created, so
/// renaming a template does not orphan the sessions that were summarised
/// with it.
class CustomSummaryTemplate {
  final String id;
  final String name;

  /// The instruction sent to the model, verbatim.
  final String instructions;

  /// Section headings, used to prefill `instructions` when the user starts
  /// from a built-in and to show the shape of the output in the picker.
  final List<String> headings;

  const CustomSummaryTemplate({
    required this.id,
    required this.name,
    required this.instructions,
    required this.headings,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ instructions.hashCode ^ headings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomSummaryTemplate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          instructions == other.instructions &&
          headings == other.headings;
}

/// Persisted state of the kamus istilah (F3).
class GlossarySettings {
  /// Master switch for feeding the terms into `initial_prompt`.
  final bool enabled;

  /// The global term list, in the order the user arranged it.
  final List<String> terms;

  /// Also run the conservative fuzzy post-correction pass.
  final bool postCorrection;

  /// Word replacements the user taught the app by correcting the
  /// transcript ("Ganti otomatis selanjutnya"). See
  /// [`crate::glossary::ReplacementRule`].
  final List<ReplacementRule> replacements;

  const GlossarySettings({
    required this.enabled,
    required this.terms,
    required this.postCorrection,
    required this.replacements,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      terms.hashCode ^
      postCorrection.hashCode ^
      replacements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GlossarySettings &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          terms == other.terms &&
          postCorrection == other.postCorrection &&
          replacements == other.replacements;
}

/// Fields of the official notulen that belong to the office, not the meeting.
class NotulenDefaults {
  final String unitKerja;
  final String tempat;
  final String notulis;

  /// Absolute path to a letterhead image (PNG/JPEG). Empty = no kop surat.
  final String kopSuratPath;

  const NotulenDefaults({
    required this.unitKerja,
    required this.tempat,
    required this.notulis,
    required this.kopSuratPath,
  });

  @override
  int get hashCode =>
      unitKerja.hashCode ^
      tempat.hashCode ^
      notulis.hashCode ^
      kopSuratPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotulenDefaults &&
          runtimeType == other.runtimeType &&
          unitKerja == other.unitKerja &&
          tempat == other.tempat &&
          notulis == other.notulis &&
          kopSuratPath == other.kopSuratPath;
}

/// Persisted configuration for the opt-in AI summary feature.
///
/// `api_key` is stored in the same plaintext settings JSON as everything
/// else (OS config dir, user-private permissions). There is no OS keychain
/// dependency in this project, so this is a deliberate trade-off: it is
/// documented in `SECURITY.md`, the field is empty by default, and the
/// default provider (local Ollama) needs no key at all.
class SummarySettings {
  /// Master switch. While false, no summary UI is offered and no request
  /// can be made — the app stays fully offline.
  final bool enabled;
  final SummaryProvider provider;
  final String baseUrl;
  final String apiKey;
  final String model;
  final SummaryTemplate template;
  final String customPrompt;

  /// Ask the model to cite the transcript segment behind each point,
  /// and render those as links that jump the player there (F7).
  final bool withCitations;

  /// Ask for the structured tugas / PJ / tenggat checklist (F6).
  final bool withActionItems;

  const SummarySettings({
    required this.enabled,
    required this.provider,
    required this.baseUrl,
    required this.apiKey,
    required this.model,
    required this.template,
    required this.customPrompt,
    required this.withCitations,
    required this.withActionItems,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      provider.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      model.hashCode ^
      template.hashCode ^
      customPrompt.hashCode ^
      withCitations.hashCode ^
      withActionItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SummarySettings &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          model == other.model &&
          template == other.template &&
          customPrompt == other.customPrompt &&
          withCitations == other.withCitations &&
          withActionItems == other.withActionItems;
}

/// Appearance preference. `System` follows the OS setting; it is a UI
/// concept, but it has to be persisted here or it silently degrades to
/// "Terang" on every restart — which is what it used to do, because the Dart
/// bridge had nowhere to map it to.
///
/// `Default` is `Light` so that a settings file written by an older build
/// (where the field could be absent) still loads.
enum Theme { light, dark, system }
