// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'audio.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'summary.dart';

class AppSettings {
  final Theme theme;
  final String defaultModel;
  final SessionMode defaultMode;
  final String libraryPath;
  final bool alwaysOnTop;
  final int autoSaveIntervalSecs;
  final bool vadEnabled;
  final bool echoDedupeEnabled;
  final String? language;

  /// Enable GPU acceleration for whisper inference (Vulkan/CUDA/Metal,
  /// whichever backend the binary was compiled with). Defaults to false
  /// so behavior is unchanged for existing installs/settings files —
  /// this is opt-in, not auto-detected, because GPU inference can be
  /// slower than CPU on low-VRAM devices once model weights don't fit.
  final bool gpuEnabled;

  /// GPU device index to use when `gpu_enabled` is true (0 = default).
  final int gpuDevice;

  /// Stop recording automatically after this many minutes without new
  /// transcript segments. `None` = never. Previously Dart-only, which meant
  /// it silently reset to "off" on every launch.
  final int? autoStopMinutes;

  /// Hybrid Progressive Transcription: quick (base) pass then refine (q5).
  final bool progressiveEnabled;

  /// Stream captured audio straight to disk instead of buffering it in
  /// RAM until Stop. On by default; see `audio::SessionConfig` for why
  /// it is a switch at all.
  final bool audioToDisk;

  /// AI summary endpoint configuration. Opt-in; see `crate::summary`.
  final SummarySettings summary;

  const AppSettings({
    required this.theme,
    required this.defaultModel,
    required this.defaultMode,
    required this.libraryPath,
    required this.alwaysOnTop,
    required this.autoSaveIntervalSecs,
    required this.vadEnabled,
    required this.echoDedupeEnabled,
    this.language,
    required this.gpuEnabled,
    required this.gpuDevice,
    this.autoStopMinutes,
    required this.progressiveEnabled,
    required this.audioToDisk,
    required this.summary,
  });

  @override
  int get hashCode =>
      theme.hashCode ^
      defaultModel.hashCode ^
      defaultMode.hashCode ^
      libraryPath.hashCode ^
      alwaysOnTop.hashCode ^
      autoSaveIntervalSecs.hashCode ^
      vadEnabled.hashCode ^
      echoDedupeEnabled.hashCode ^
      language.hashCode ^
      gpuEnabled.hashCode ^
      gpuDevice.hashCode ^
      autoStopMinutes.hashCode ^
      progressiveEnabled.hashCode ^
      audioToDisk.hashCode ^
      summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          defaultModel == other.defaultModel &&
          defaultMode == other.defaultMode &&
          libraryPath == other.libraryPath &&
          alwaysOnTop == other.alwaysOnTop &&
          autoSaveIntervalSecs == other.autoSaveIntervalSecs &&
          vadEnabled == other.vadEnabled &&
          echoDedupeEnabled == other.echoDedupeEnabled &&
          language == other.language &&
          gpuEnabled == other.gpuEnabled &&
          gpuDevice == other.gpuDevice &&
          autoStopMinutes == other.autoStopMinutes &&
          progressiveEnabled == other.progressiveEnabled &&
          audioToDisk == other.audioToDisk &&
          summary == other.summary;
}

/// Persisted configuration for the opt-in AI summary feature.
///
/// `api_key` is stored in the same plaintext settings JSON as everything
/// else (OS config dir, user-private permissions). There is no OS keychain
/// dependency in this project, so this is a deliberate trade-off: it is
/// documented in `SECURITY.md`, the field is empty by default, and the
/// default provider (local Ollama) needs no key at all.
class SummarySettings {
  /// Master switch. While false, no summary UI is offered and no request
  /// can be made — the app stays fully offline.
  final bool enabled;
  final SummaryProvider provider;
  final String baseUrl;
  final String apiKey;
  final String model;
  final SummaryTemplate template;
  final String customPrompt;

  const SummarySettings({
    required this.enabled,
    required this.provider,
    required this.baseUrl,
    required this.apiKey,
    required this.model,
    required this.template,
    required this.customPrompt,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      provider.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      model.hashCode ^
      template.hashCode ^
      customPrompt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SummarySettings &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          model == other.model &&
          template == other.template &&
          customPrompt == other.customPrompt;
}

/// Appearance preference. `System` follows the OS setting; it is a UI
/// concept, but it has to be persisted here or it silently degrades to
/// "Terang" on every restart — which is what it used to do, because the Dart
/// bridge had nowhere to map it to.
///
/// `Default` is `Light` so that a settings file written by an older build
/// (where the field could be absent) still loads.
enum Theme { light, dark, system }
