// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Klasifikasi keamanan dan akses.
enum KlasifikasiKeamanan { sangatRahasia, rahasia, terbatas, biasa }

/// Kecepatan penyampaian, per the Pedoman Tata Naskah Dinas.
enum Sifat {
  /// 24 jam.
  sangatSegera,

  /// 2 × 24 jam.
  segera,
  biasa,
}

/// Everything SRIKANDI's registration form asks for that a notulen does
/// not already state.
class SrikandiMetadata {
  /// Nomor naskah, from the unit's Tata Usaha. Never generated.
  final String nomor;

  /// Written date, e.g. "5 Oktober 2026".
  final String tanggal;

  /// Jenis naskah dinas, e.g. "Notula Rapat".
  final String jenisNaskah;

  /// Hal / perihal, one line, no trailing full stop.
  final String perihal;
  final Sifat sifat;
  final KlasifikasiKeamanan klasifikasiKeamanan;

  /// Kode klasifikasi arsip, e.g. "UM.03.01". From the unit's
  /// klasifikasi-arsip pedoman, not derivable from the document.
  final String kodeKlasifikasiArsip;

  /// Unit pengolah — the unit that created the naskah.
  final String unitPengolah;
  final String penandatanganNama;
  final String penandatanganJabatan;
  final int jumlahLampiran;
  final TingkatPerkembangan tingkatPerkembangan;

  /// Free-text note carried into the sidecar, e.g. a retention remark.
  final String catatan;

  const SrikandiMetadata({
    required this.nomor,
    required this.tanggal,
    required this.jenisNaskah,
    required this.perihal,
    required this.sifat,
    required this.klasifikasiKeamanan,
    required this.kodeKlasifikasiArsip,
    required this.unitPengolah,
    required this.penandatanganNama,
    required this.penandatanganJabatan,
    required this.jumlahLampiran,
    required this.tingkatPerkembangan,
    required this.catatan,
  });

  @override
  int get hashCode =>
      nomor.hashCode ^
      tanggal.hashCode ^
      jenisNaskah.hashCode ^
      perihal.hashCode ^
      sifat.hashCode ^
      klasifikasiKeamanan.hashCode ^
      kodeKlasifikasiArsip.hashCode ^
      unitPengolah.hashCode ^
      penandatanganNama.hashCode ^
      penandatanganJabatan.hashCode ^
      jumlahLampiran.hashCode ^
      tingkatPerkembangan.hashCode ^
      catatan.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SrikandiMetadata &&
          runtimeType == other.runtimeType &&
          nomor == other.nomor &&
          tanggal == other.tanggal &&
          jenisNaskah == other.jenisNaskah &&
          perihal == other.perihal &&
          sifat == other.sifat &&
          klasifikasiKeamanan == other.klasifikasiKeamanan &&
          kodeKlasifikasiArsip == other.kodeKlasifikasiArsip &&
          unitPengolah == other.unitPengolah &&
          penandatanganNama == other.penandatanganNama &&
          penandatanganJabatan == other.penandatanganJabatan &&
          jumlahLampiran == other.jumlahLampiran &&
          tingkatPerkembangan == other.tingkatPerkembangan &&
          catatan == other.catatan;
}

/// One thing wrong with the metadata.
class TemuanMetadata {
  final String bidang;
  final Tingkat tingkat;
  final String pesan;

  const TemuanMetadata({
    required this.bidang,
    required this.tingkat,
    required this.pesan,
  });

  @override
  int get hashCode => bidang.hashCode ^ tingkat.hashCode ^ pesan.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemuanMetadata &&
          runtimeType == other.runtimeType &&
          bidang == other.bidang &&
          tingkat == other.tingkat &&
          pesan == other.pesan;
}

/// How serious a validation finding is.
enum Tingkat {
  /// The sidecar cannot be registered without this.
  wajib,

  /// Registration will work; an archivist will ask about it.
  saran,
}

/// Tingkat perkembangan naskah.
enum TingkatPerkembangan { asli, salinan, tembusan, pertinggal }
