// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SummaryConfig {
  final SummaryProvider provider;

  /// e.g. `http://localhost:11434` or `https://api.openai.com/v1`.
  final String baseUrl;

  /// Bearer token for OpenAI-compatible endpoints. Empty for Ollama.
  final String apiKey;

  /// e.g. `qwen2.5:7b`, `gpt-4o-mini`.
  final String model;
  final SummaryTemplate template;

  /// Instruction used when `template == Kustom`.
  final String customPrompt;

  /// Output language: `"id"` or `"en"`.
  final String language;
  final BigInt timeoutSecs;

  const SummaryConfig({
    required this.provider,
    required this.baseUrl,
    required this.apiKey,
    required this.model,
    required this.template,
    required this.customPrompt,
    required this.language,
    required this.timeoutSecs,
  });

  @override
  int get hashCode =>
      provider.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      model.hashCode ^
      template.hashCode ^
      customPrompt.hashCode ^
      language.hashCode ^
      timeoutSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SummaryConfig &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          model == other.model &&
          template == other.template &&
          customPrompt == other.customPrompt &&
          language == other.language &&
          timeoutSecs == other.timeoutSecs;
}

enum SummaryProvider { ollama, openAiCompatible }

/// Indonesian meeting-summary templates. `Kustom` uses
/// [`SummaryConfig::custom_prompt`] verbatim as the instruction.
enum SummaryTemplate {
  /// Full minutes: agenda, discussion, decisions, follow-ups.
  notulenRapat,

  /// Short prose brief for someone who wasn't there.
  ringkasanEksekutif,

  /// Decisions and action items only, with owners.
  actionItems,

  /// Daily-standup shape: done / next / blockers, per person.
  standup,
  kustom,
}
