// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `client`, `request_body`, `snippet`, `trim_base`, `validate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `build_prompt`, `chat_endpoint`, `models_endpoint`, `parse_chat_response`, `parse_models_response`, `system_prompt`, `template_instruction`, `transcript_text`, `truncate_transcript`

/// Sends `transcript` to the configured endpoint and returns Markdown.
///
/// This is the only place in the crate that performs an outbound request
/// with user content, and it runs exactly once per explicit user action.
Future<String> generateSummary({
  required SummaryConfig config,
  required String transcript,
}) => RustLib.instance.api.crateSummaryGenerateSummary(
  config: config,
  transcript: transcript,
);

/// Lists the models the configured endpoint offers, so the UI can present a
/// dropdown instead of a free-text field. Sends no transcript content.
Future<List<String>> listSummaryModels({
  required SummaryProvider provider,
  required String baseUrl,
  required String apiKey,
}) => RustLib.instance.api.crateSummaryListSummaryModels(
  provider: provider,
  baseUrl: baseUrl,
  apiKey: apiKey,
);

class SummaryConfig {
  final SummaryProvider provider;

  /// e.g. `http://localhost:11434` or `https://api.openai.com/v1`.
  final String baseUrl;

  /// Bearer token for OpenAI-compatible endpoints. Empty for Ollama.
  final String apiKey;

  /// e.g. `qwen2.5:7b`, `gpt-4o-mini`.
  final String model;
  final SummaryTemplate template;

  /// Instruction used when `template == Kustom`.
  final String customPrompt;

  /// Output language: `"id"` or `"en"`.
  final String language;
  final BigInt timeoutSecs;

  const SummaryConfig({
    required this.provider,
    required this.baseUrl,
    required this.apiKey,
    required this.model,
    required this.template,
    required this.customPrompt,
    required this.language,
    required this.timeoutSecs,
  });

  static Future<SummaryConfig> default_() =>
      RustLib.instance.api.crateSummarySummaryConfigDefault();

  @override
  int get hashCode =>
      provider.hashCode ^
      baseUrl.hashCode ^
      apiKey.hashCode ^
      model.hashCode ^
      template.hashCode ^
      customPrompt.hashCode ^
      language.hashCode ^
      timeoutSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SummaryConfig &&
          runtimeType == other.runtimeType &&
          provider == other.provider &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey &&
          model == other.model &&
          template == other.template &&
          customPrompt == other.customPrompt &&
          language == other.language &&
          timeoutSecs == other.timeoutSecs;
}

enum SummaryProvider { ollama, openAiCompatible }

/// Indonesian meeting-summary templates. `Kustom` uses
/// [`SummaryConfig::custom_prompt`] verbatim as the instruction.
enum SummaryTemplate {
  /// Full minutes: agenda, discussion, decisions, follow-ups.
  notulenRapat,

  /// Short prose brief for someone who wasn't there.
  ringkasanEksekutif,

  /// Decisions and action items only, with owners.
  actionItems,

  /// Daily-standup shape: done / next / blockers, per person.
  standup,
  kustom,
}
