// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../notulen.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Prefill for the notulen form, parsed out of an AI summary.
class NotulenDraft {
  final String pembahasan;
  final List<String> keputusan;
  final List<TindakLanjut> tindakLanjut;
  final List<String> peserta;

  const NotulenDraft({
    required this.pembahasan,
    required this.keputusan,
    required this.tindakLanjut,
    required this.peserta,
  });

  @override
  int get hashCode =>
      pembahasan.hashCode ^
      keputusan.hashCode ^
      tindakLanjut.hashCode ^
      peserta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotulenDraft &&
          runtimeType == other.runtimeType &&
          pembahasan == other.pembahasan &&
          keputusan == other.keputusan &&
          tindakLanjut == other.tindakLanjut &&
          peserta == other.peserta;
}

/// Everything the notulen needs that the audio cannot supply, plus the body
/// sections derived from the summary.
///
/// Persisted with the session (see `session_store.dart`) so re-exporting a
/// meeting six months later reproduces the same document.
class NotulenForm {
  /// Which naskah-dinas layout to render.
  ///
  /// `alias = "variant"` migrates sessions saved before Sprint 7, when
  /// this was a two-value `NotulenVariant`. Both of its names —
  /// `Dinas`, `Ringkas` — are still names of
  /// [`crate::notulen::NotulenTemplate`] variants, so an old
  /// `transcript.json` deserialises unchanged.
  final NotulenTemplate template;

  /// Kop surat first line, e.g. "KEMENTERIAN KEUANGAN REPUBLIK INDONESIA".
  final String instansi;

  /// Kop surat second line, e.g. "DIREKTORAT JENDERAL ANGGARAN".
  final String unitKerja;

  /// Nomor notulen, e.g. "ND-12/AG.3/2026".
  final String nomor;
  final String judul;

  /// Day name, e.g. "Senin".
  final String hari;

  /// Written date, e.g. "1 Oktober 2026".
  final String tanggal;

  /// e.g. "09.00 – 11.30 WIB".
  final String waktu;

  /// Place or platform, e.g. "Ruang Rapat Lt. 5 / Zoom".
  final String tempat;
  final String pimpinan;
  final String notulis;
  final List<String> peserta;
  final List<String> agenda;

  /// Two or three sentences of context, printed above Pembahasan.
  /// Empty = the section is omitted entirely.
  final String ringkasan;

  /// Discussion body, Markdown (normally the AI summary's "Pembahasan").
  final String pembahasan;

  /// Risalah Rapat only: the ordered record of interventions. Ignored
  /// by the other templates.
  final List<RisalahEntry> jalannyaRapat;

  /// Berita Acara only: "kami yang bertanda tangan di bawah ini".
  /// Ignored by the other templates.
  final List<String> pihak;
  final List<String> keputusan;
  final List<TindakLanjut> tindakLanjut;

  /// Bookmarks the notulis dropped during the meeting, rendered as
  /// "Poin Penting". Already formatted as `"[mm:ss] catatan"`.
  final List<String> poinPenting;

  /// Absolute path to a PNG letterhead. Empty = render the kop surat as
  /// text from `instansi` / `unit_kerja`.
  final String kopSuratPath;

  /// Append the full transcript as "Lampiran: Transkrip".
  final bool lampirkanTranskrip;

  const NotulenForm({
    required this.template,
    required this.instansi,
    required this.unitKerja,
    required this.nomor,
    required this.judul,
    required this.hari,
    required this.tanggal,
    required this.waktu,
    required this.tempat,
    required this.pimpinan,
    required this.notulis,
    required this.peserta,
    required this.agenda,
    required this.ringkasan,
    required this.pembahasan,
    required this.jalannyaRapat,
    required this.pihak,
    required this.keputusan,
    required this.tindakLanjut,
    required this.poinPenting,
    required this.kopSuratPath,
    required this.lampirkanTranskrip,
  });

  @override
  int get hashCode =>
      template.hashCode ^
      instansi.hashCode ^
      unitKerja.hashCode ^
      nomor.hashCode ^
      judul.hashCode ^
      hari.hashCode ^
      tanggal.hashCode ^
      waktu.hashCode ^
      tempat.hashCode ^
      pimpinan.hashCode ^
      notulis.hashCode ^
      peserta.hashCode ^
      agenda.hashCode ^
      ringkasan.hashCode ^
      pembahasan.hashCode ^
      jalannyaRapat.hashCode ^
      pihak.hashCode ^
      keputusan.hashCode ^
      tindakLanjut.hashCode ^
      poinPenting.hashCode ^
      kopSuratPath.hashCode ^
      lampirkanTranskrip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotulenForm &&
          runtimeType == other.runtimeType &&
          template == other.template &&
          instansi == other.instansi &&
          unitKerja == other.unitKerja &&
          nomor == other.nomor &&
          judul == other.judul &&
          hari == other.hari &&
          tanggal == other.tanggal &&
          waktu == other.waktu &&
          tempat == other.tempat &&
          pimpinan == other.pimpinan &&
          notulis == other.notulis &&
          peserta == other.peserta &&
          agenda == other.agenda &&
          ringkasan == other.ringkasan &&
          pembahasan == other.pembahasan &&
          jalannyaRapat == other.jalannyaRapat &&
          pihak == other.pihak &&
          keputusan == other.keputusan &&
          tindakLanjut == other.tindakLanjut &&
          poinPenting == other.poinPenting &&
          kopSuratPath == other.kopSuratPath &&
          lampirkanTranskrip == other.lampirkanTranskrip;
}

/// One intervention in a risalah: who said what, in order.
///
/// Flat strings rather than [`crate::notulen::schema::Intervensi`]: the
/// document shows no segment numbers, and the form the user edits before
/// export should not carry fields the document cannot display.
class RisalahEntry {
  final String pembicara;
  final String pokok;

  const RisalahEntry({required this.pembicara, required this.pokok});

  @override
  int get hashCode => pembicara.hashCode ^ pokok.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RisalahEntry &&
          runtimeType == other.runtimeType &&
          pembicara == other.pembicara &&
          pokok == other.pokok;
}

/// One row of the "Tindak Lanjut" table.
class TindakLanjut {
  final String tugas;
  final String penanggungJawab;
  final String tenggat;

  const TindakLanjut({
    required this.tugas,
    required this.penanggungJawab,
    required this.tenggat,
  });

  @override
  int get hashCode =>
      tugas.hashCode ^ penanggungJawab.hashCode ^ tenggat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TindakLanjut &&
          runtimeType == other.runtimeType &&
          tugas == other.tugas &&
          penanggungJawab == other.penanggungJawab &&
          tenggat == other.tenggat;
}
