// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Prefill for the notulen form, parsed out of an AI summary.
class NotulenDraft {
  final String pembahasan;
  final List<String> keputusan;
  final List<TindakLanjut> tindakLanjut;
  final List<String> peserta;

  const NotulenDraft({
    required this.pembahasan,
    required this.keputusan,
    required this.tindakLanjut,
    required this.peserta,
  });

  @override
  int get hashCode =>
      pembahasan.hashCode ^
      keputusan.hashCode ^
      tindakLanjut.hashCode ^
      peserta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotulenDraft &&
          runtimeType == other.runtimeType &&
          pembahasan == other.pembahasan &&
          keputusan == other.keputusan &&
          tindakLanjut == other.tindakLanjut &&
          peserta == other.peserta;
}

/// Everything the notulen needs that the audio cannot supply, plus the body
/// sections derived from the summary.
///
/// Persisted with the session (see `session_store.dart`) so re-exporting a
/// meeting six months later reproduces the same document.
class NotulenForm {
  final NotulenVariant variant;

  /// Kop surat first line, e.g. "KEMENTERIAN KEUANGAN REPUBLIK INDONESIA".
  final String instansi;

  /// Kop surat second line, e.g. "DIREKTORAT JENDERAL ANGGARAN".
  final String unitKerja;

  /// Nomor notulen, e.g. "ND-12/AG.3/2026".
  final String nomor;
  final String judul;

  /// Day name, e.g. "Senin".
  final String hari;

  /// Written date, e.g. "1 Oktober 2026".
  final String tanggal;

  /// e.g. "09.00 – 11.30 WIB".
  final String waktu;

  /// Place or platform, e.g. "Ruang Rapat Lt. 5 / Zoom".
  final String tempat;
  final String pimpinan;
  final String notulis;
  final List<String> peserta;
  final List<String> agenda;

  /// Discussion body, Markdown (normally the AI summary's "Pembahasan").
  final String pembahasan;
  final List<String> keputusan;
  final List<TindakLanjut> tindakLanjut;

  /// Bookmarks the notulis dropped during the meeting, rendered as
  /// "Poin Penting". Already formatted as `"[mm:ss] catatan"`.
  final List<String> poinPenting;

  /// Absolute path to a PNG letterhead. Empty = render the kop surat as
  /// text from `instansi` / `unit_kerja`.
  final String kopSuratPath;

  /// Append the full transcript as "Lampiran: Transkrip".
  final bool lampirkanTranskrip;

  const NotulenForm({
    required this.variant,
    required this.instansi,
    required this.unitKerja,
    required this.nomor,
    required this.judul,
    required this.hari,
    required this.tanggal,
    required this.waktu,
    required this.tempat,
    required this.pimpinan,
    required this.notulis,
    required this.peserta,
    required this.agenda,
    required this.pembahasan,
    required this.keputusan,
    required this.tindakLanjut,
    required this.poinPenting,
    required this.kopSuratPath,
    required this.lampirkanTranskrip,
  });

  @override
  int get hashCode =>
      variant.hashCode ^
      instansi.hashCode ^
      unitKerja.hashCode ^
      nomor.hashCode ^
      judul.hashCode ^
      hari.hashCode ^
      tanggal.hashCode ^
      waktu.hashCode ^
      tempat.hashCode ^
      pimpinan.hashCode ^
      notulis.hashCode ^
      peserta.hashCode ^
      agenda.hashCode ^
      pembahasan.hashCode ^
      keputusan.hashCode ^
      tindakLanjut.hashCode ^
      poinPenting.hashCode ^
      kopSuratPath.hashCode ^
      lampirkanTranskrip.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotulenForm &&
          runtimeType == other.runtimeType &&
          variant == other.variant &&
          instansi == other.instansi &&
          unitKerja == other.unitKerja &&
          nomor == other.nomor &&
          judul == other.judul &&
          hari == other.hari &&
          tanggal == other.tanggal &&
          waktu == other.waktu &&
          tempat == other.tempat &&
          pimpinan == other.pimpinan &&
          notulis == other.notulis &&
          peserta == other.peserta &&
          agenda == other.agenda &&
          pembahasan == other.pembahasan &&
          keputusan == other.keputusan &&
          tindakLanjut == other.tindakLanjut &&
          poinPenting == other.poinPenting &&
          kopSuratPath == other.kopSuratPath &&
          lampirkanTranskrip == other.lampirkanTranskrip;
}

/// Which of the two shipped layouts to render.
///
/// Tata Naskah Dinas varies per ministry and pemda, so the strategy from the
/// blueprint is two variants rather than one "correct" template: the full
/// dinas form for archiving, and a one-page ringkas form for circulation.
enum NotulenVariant {
  /// Full Tata Naskah Dinas layout: kop surat, nomor, identity table,
  /// agenda, pembahasan, keputusan, tindak lanjut table, signature block.
  dinas,

  /// One page, no kop surat and no signature block — for circulating the
  /// outcome quickly.
  ringkas,
}

/// One row of the "Tindak Lanjut" table.
class TindakLanjut {
  final String tugas;
  final String penanggungJawab;
  final String tenggat;

  const TindakLanjut({
    required this.tugas,
    required this.penanggungJawab,
    required this.tenggat,
  });

  @override
  int get hashCode =>
      tugas.hashCode ^ penanggungJawab.hashCode ^ tenggat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TindakLanjut &&
          runtimeType == other.runtimeType &&
          tugas == other.tugas &&
          penanggungJawab == other.penanggungJawab &&
          tenggat == other.tenggat;
}
