// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../export.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class TranscribeFileResult {
  final String filename;
  final double durationSecs;
  final List<Segment> segments;
  final String language;

  const TranscribeFileResult({
    required this.filename,
    required this.durationSecs,
    required this.segments,
    required this.language,
  });

  @override
  int get hashCode =>
      filename.hashCode ^
      durationSecs.hashCode ^
      segments.hashCode ^
      language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscribeFileResult &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          durationSecs == other.durationSecs &&
          segments == other.segments &&
          language == other.language;
}
