// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AudioDeviceInfo {
  final String name;
  final String deviceId;
  final bool isDefault;
  final int channels;
  final Uint32List sampleRates;

  const AudioDeviceInfo({
    required this.name,
    required this.deviceId,
    required this.isDefault,
    required this.channels,
    required this.sampleRates,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      deviceId.hashCode ^
      isDefault.hashCode ^
      channels.hashCode ^
      sampleRates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDeviceInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          deviceId == other.deviceId &&
          isDefault == other.isDefault &&
          channels == other.channels &&
          sampleRates == other.sampleRates;
}
