// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// One kind of act worth recording.
enum AuditAction {
  sessionCreated,
  sessionExported,
  summarySent,
  sessionDeleted,
  audioDeleted,
  transcriptDeleted,
  consentAcknowledged,
  redactionApplied,
  retentionApplied,
  auditExported,

  /// A notulen model was downloaded to the summary endpoint.
  modelPulled,

  /// A local document was used as notulen context.
  documentContextUsed,

  /// A background pass with a more accurate model replaced a session's
  /// transcript (F5).
  transcriptEnhanced,
}

/// One line of the log.
class AuditEntry {
  final BigInt atUnixMs;
  final AuditAction action;

  /// Who: the OS account the app ran as. There is no other actor on a
  /// desktop app, and inventing one would be theatre.
  final String actor;

  /// What it was about — a session title or directory name. Never
  /// transcript text.
  final String subject;

  /// Where it went, for the acts that move data: an output directory, a
  /// summary endpoint host. Never a full URL with a query string.
  final String destination;

  /// One short free-text note, e.g. "3 NIK, 1 email".
  final String detail;

  const AuditEntry({
    required this.atUnixMs,
    required this.action,
    required this.actor,
    required this.subject,
    required this.destination,
    required this.detail,
  });

  @override
  int get hashCode =>
      atUnixMs.hashCode ^
      action.hashCode ^
      actor.hashCode ^
      subject.hashCode ^
      destination.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuditEntry &&
          runtimeType == other.runtimeType &&
          atUnixMs == other.atUnixMs &&
          action == other.action &&
          actor == other.actor &&
          subject == other.subject &&
          destination == other.destination &&
          detail == other.detail;
}
