// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// What a match is, which decides its placeholder and its precedence.
enum PiiKind {
  /// Nomor Induk Kependudukan — 16 digits.
  nik,

  /// Nomor Pokok Wajib Pajak — 15 digits, often dotted.
  npwp,
  phone,
  email,

  /// A digit run a bank keyword vouches for.
  bankAccount,

  /// A name the user put on the list.
  name,
}

/// One thing that would be masked. Byte offsets into the text scanned, so
/// the UI can highlight in place.
class PiiMatch {
  final PiiKind kind;
  final int start;
  final int end;

  /// The text as it appears, for the preview. This is itself personal
  /// data: it is shown to the user who already has the transcript open
  /// and is never written anywhere.
  final String text;
  final String replacement;

  const PiiMatch({
    required this.kind,
    required this.start,
    required this.end,
    required this.text,
    required this.replacement,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      start.hashCode ^
      end.hashCode ^
      text.hashCode ^
      replacement.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PiiMatch &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          start == other.start &&
          end == other.end &&
          text == other.text &&
          replacement == other.replacement;
}

/// Which categories to mask, plus the names only this user can know about.
class RedactionConfig {
  final bool nik;
  final bool npwp;
  final bool phone;
  final bool email;
  final bool bankAccount;

  /// Names to mask wherever they appear. Matched whole-word and
  /// case-insensitively; a one- or two-character entry is ignored,
  /// because masking every "di" in the transcript is not redaction.
  final List<String> names;

  const RedactionConfig({
    required this.nik,
    required this.npwp,
    required this.phone,
    required this.email,
    required this.bankAccount,
    required this.names,
  });

  @override
  int get hashCode =>
      nik.hashCode ^
      npwp.hashCode ^
      phone.hashCode ^
      email.hashCode ^
      bankAccount.hashCode ^
      names.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedactionConfig &&
          runtimeType == other.runtimeType &&
          nik == other.nik &&
          npwp == other.npwp &&
          phone == other.phone &&
          email == other.email &&
          bankAccount == other.bankAccount &&
          names == other.names;
}
