// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RetentionItem {
  final String path;
  final String title;

  /// How many days past the limit it is, for the preview.
  final int ageDays;
  final BigInt bytes;

  const RetentionItem({
    required this.path,
    required this.title,
    required this.ageDays,
    required this.bytes,
  });

  @override
  int get hashCode =>
      path.hashCode ^ title.hashCode ^ ageDays.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetentionItem &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          ageDays == other.ageDays &&
          bytes == other.bytes;
}

class RetentionOutcome {
  final List<String> deleted;
  final List<String> failed;

  const RetentionOutcome({required this.deleted, required this.failed});

  @override
  int get hashCode => deleted.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetentionOutcome &&
          runtimeType == other.runtimeType &&
          deleted == other.deleted &&
          failed == other.failed;
}

/// What would be deleted, and why.
class RetentionPlan {
  /// Audio files to delete, leaving the transcript behind.
  final List<RetentionItem> audioToDelete;

  /// Whole session folders to delete.
  final List<RetentionItem> sessionsToDelete;

  /// Bytes the audio deletions would free.
  final BigInt audioBytesFreed;

  const RetentionPlan({
    required this.audioToDelete,
    required this.sessionsToDelete,
    required this.audioBytesFreed,
  });

  @override
  int get hashCode =>
      audioToDelete.hashCode ^
      sessionsToDelete.hashCode ^
      audioBytesFreed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetentionPlan &&
          runtimeType == other.runtimeType &&
          audioToDelete == other.audioToDelete &&
          sessionsToDelete == other.sessionsToDelete &&
          audioBytesFreed == other.audioBytesFreed;
}

class RetentionPolicy {
  /// Delete captured audio older than this many days. `0` = keep
  /// forever, which is the default and must stay the default.
  final int audioDays;

  /// Delete the transcript (and the whole session folder with it) older
  /// than this many days. `0` = keep forever.
  final int transcriptDays;

  const RetentionPolicy({
    required this.audioDays,
    required this.transcriptDays,
  });

  @override
  int get hashCode => audioDays.hashCode ^ transcriptDays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetentionPolicy &&
          runtimeType == other.runtimeType &&
          audioDays == other.audioDays &&
          transcriptDays == other.transcriptDays;
}

/// One session as the planner sees it. Deliberately not a `SessionRecord`:
/// the planner must be testable without a library on disk.
class SessionAge {
  final String dirPath;
  final String title;

  /// When the session was recorded, in milliseconds since the epoch.
  final BigInt recordedAtUnixMs;

  /// Captured audio files inside the session folder.
  final List<String> audioPaths;
  final BigInt audioBytes;

  const SessionAge({
    required this.dirPath,
    required this.title,
    required this.recordedAtUnixMs,
    required this.audioPaths,
    required this.audioBytes,
  });

  @override
  int get hashCode =>
      dirPath.hashCode ^
      title.hashCode ^
      recordedAtUnixMs.hashCode ^
      audioPaths.hashCode ^
      audioBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionAge &&
          runtimeType == other.runtimeType &&
          dirPath == other.dirPath &&
          title == other.title &&
          recordedAtUnixMs == other.recordedAtUnixMs &&
          audioPaths == other.audioPaths &&
          audioBytes == other.audioBytes;
}
